#!/usr/bin/env bash
set -Eeuo pipefail

repo_root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd)"
tmp="$(mktemp -d)"
trap 'rm -rf -- "$tmp"' EXIT

make_fixture() {
	local name="$1" fixture
	fixture="$tmp/$name"
	mkdir -p "$fixture/ops"
	cp "$repo_root/ops/configure-cluster-node.sh" "$repo_root/ops/generate-woodpecker-workflows.sh" "$fixture/ops/"
	cp "$repo_root/ops/images.apps.prod.env" "$fixture/ops/"
	cp -R "$repo_root/apps" "$repo_root/config" "$fixture/"
	# The repository reserves worker-3; this suite exercises adding it from a
	# three-node baseline, so remove the committed reservation in the fixture.
	rm -f "$fixture/config/cluster/nodes/worker-3.env"
	rm -f "$fixture/config/cluster/nodes/worker-4.env"
	sed 's/,worker-3,worker-4$//' "$fixture/config/cluster/policy.env" >"$fixture/config/cluster/policy.env.tmp"
	mv "$fixture/config/cluster/policy.env.tmp" "$fixture/config/cluster/policy.env"
	# The lifecycle fixture promotes a previously unknown node from joining;
	# keep the committed worker-3 Flowy placement out of this reduced inventory.
	sed 's/^ENABLED=true$/ENABLED=false/' "$fixture/config/cluster/apps/flowy.policy" >"$fixture/config/cluster/apps/flowy.policy.tmp"
	mv "$fixture/config/cluster/apps/flowy.policy.tmp" "$fixture/config/cluster/apps/flowy.policy"
	sed 's/^NODES=.*/NODES=worker-2/' "$fixture/config/cluster/apps/wabase.policy" >"$fixture/config/cluster/apps/wabase.policy.tmp"
	mv "$fixture/config/cluster/apps/wabase.policy.tmp" "$fixture/config/cluster/apps/wabase.policy"
	printf '%s\n' "$fixture"
}
run_add() {
	local fixture="$1" node="$2"
	DOMAIN_NAME=example.test CLUSTER_NODE_ASSUME_YES=1 bash "$fixture/ops/configure-cluster-node.sh" add "$node"
}
run_add_domain() {
	local fixture="$1" node="$2" domain="$3"
	DOMAIN_NAME="$domain" CLUSTER_NODE_ASSUME_YES=1 bash "$fixture/ops/configure-cluster-node.sh" add "$node"
}
run_add_prefix() {
	local fixture="$1" node="$2" prefix="$3" domain="${4:-example.test}"
	DOMAIN_NAME="$domain" NODE_ORIGIN_PREFIX="$prefix" CLUSTER_NODE_ASSUME_YES=1 bash "$fixture/ops/configure-cluster-node.sh" add "$node"
}
expect_failure() {
	local expected="$1"
	shift
	if "$@" >"$tmp/failure.log" 2>&1; then
		printf 'cluster node command unexpectedly succeeded: %s\n' "$expected" >&2
		exit 1
	fi
	grep -Fq "$expected" "$tmp/failure.log"
}

fixture="$(make_fixture lifecycle)"
run_add "$fixture" worker-3 >/dev/null
grep -Fxq 'NODE_IDS=leader,worker-1,worker-2,worker-3' "$fixture/config/cluster/policy.env"
grep -Fxq 'NODE_ID=worker-3' "$fixture/config/cluster/nodes/worker-3.env"
grep -Fxq 'NODE_STATE=joining' "$fixture/config/cluster/nodes/worker-3.env"
grep -Fxq 'NODE_LIBRECHAT_ORIGIN_HOST=worker3-chat-origin.example.test' "$fixture/config/cluster/nodes/worker-3.env"
grep -Fxq 'NODE_LIBRECHAT_ADMIN_ORIGIN_HOST=worker3-chat-admin-origin.example.test' "$fixture/config/cluster/nodes/worker-3.env"
grep -Fxq 'NODE_CURSORAPI_ORIGIN_HOST=worker3-cursorapi-origin.example.test' "$fixture/config/cluster/nodes/worker-3.env"
grep -Fxq 'NODE_WABASE_ORIGIN_HOST=worker3-wabase-origin.example.test' "$fixture/config/cluster/nodes/worker-3.env"
grep -Fxq 'WOODPECKER_AGENT_LABELS=node=worker-3,deployment=true,target=production,repo=uptonking/llm-hub-lite' "$fixture/config/cluster/nodes/worker-3.env"
grep -Fxq 'NEW_API_NODE_TYPE=slave' "$fixture/config/cluster/nodes/worker-3.env"
[[ -f "$fixture/.woodpecker/foundation-upgrade-worker-3.yml" ]]
[[ ! -e "$fixture/.woodpecker/consumer-secrets-cpapi-worker-3.yml" ]]
[[ ! -e "$fixture/.woodpecker/consumer-stage-librechat-worker-3.yml" ]]

expect_failure 'node already exists in NODE_IDS: worker-3' run_add "$fixture" worker-3
expect_failure 'invalid node ID: Worker_4' run_add "$fixture" Worker_4
expect_failure 'the Leader is managed only by LEADER_NODE_ID' run_add "$fixture" leader

invalid_domain="$(make_fixture invalid-domain)"
expect_failure 'DOMAIN_NAME must be a lowercase DNS name: 8.8.8.8' run_add_domain "$invalid_domain" worker-3 8.8.8.8
[[ ! -e "$invalid_domain/config/cluster/nodes/worker-3.env" ]]

collision="$(make_fixture collision)"
expect_failure 'generated origin hostname is already used by worker-1:' \
	run_add_prefix "$collision" worker-4 worker1 aichorage.de
[[ ! -e "$collision/config/cluster/nodes/worker-4.env" ]]

transaction="$(make_fixture transaction)"
cp "$transaction/config/cluster/policy.env" "$transaction/policy.before"
mkdir -p "$transaction/.woodpecker"
printf '%s\nworkflow: before\n' '# generated by ops/generate-woodpecker-workflows.sh; do not edit' >"$transaction/.woodpecker/generated-sentinel.yml"
printf '%s\nAICHOROUTER_IMAGE=before\n' '# generated by ops/generate-woodpecker-workflows.sh; do not edit' >"$transaction/apps/aichorouter/images.lock.env"
cp "$transaction/.woodpecker/generated-sentinel.yml" "$transaction/sentinel.before"
cp "$transaction/apps/aichorouter/images.lock.env" "$transaction/aichorouter-lock.before"
cat >"$transaction/ops/generate-woodpecker-workflows.sh" <<'EOF'
#!/usr/bin/env bash
set -eu
fixture_root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
printf '%s\nworkflow: mutated\n' '# generated by ops/generate-woodpecker-workflows.sh; do not edit' >"$fixture_root/.woodpecker/generated-sentinel.yml"
rm -f -- "$fixture_root/apps/aichorouter/images.lock.env"
printf '%s\nworkflow: newly-created\n' '# generated by ops/generate-woodpecker-workflows.sh; do not edit' >"$fixture_root/.woodpecker/newly-created.yml"
printf '%s\nAICHOROUTER_IMAGE=mutated\n' '# generated by ops/generate-woodpecker-workflows.sh; do not edit' >"$fixture_root/apps/aichorouter/images.lock.env"
exit 1
EOF
expect_failure 'configure-cluster-node' run_add "$transaction" worker-3
cmp -s "$transaction/policy.before" "$transaction/config/cluster/policy.env"
[[ ! -e "$transaction/config/cluster/nodes/worker-3.env" ]]
cmp -s "$transaction/sentinel.before" "$transaction/.woodpecker/generated-sentinel.yml"
cmp -s "$transaction/aichorouter-lock.before" "$transaction/apps/aichorouter/images.lock.env"
[[ ! -e "$transaction/.woodpecker/newly-created.yml" ]]
if find "$transaction/config/cluster" -type f \( -name '*.backup.*' -o -name '*.tmp.*' -o -name 'worker-3.env.*' \) | grep -q .; then
	printf 'failed node transaction left temporary files behind\n' >&2
	exit 1
fi

CLUSTER_NODE_ASSUME_YES=1 bash "$fixture/ops/configure-cluster-node.sh" state worker-3 active >/dev/null
grep -Fxq 'NODE_STATE=active' "$fixture/config/cluster/nodes/worker-3.env"
[[ -f "$fixture/.woodpecker/consumer-secrets-cpapi-worker-3.yml" ]]
[[ -f "$fixture/.woodpecker/rollback-worker-3.yml" ]]

sed 's/^NODES=.*/NODES=worker-1,worker-2,worker-3/' "$fixture/config/cluster/apps/librechat.policy" >"$fixture/librechat.policy"
mv "$fixture/librechat.policy" "$fixture/config/cluster/apps/librechat.policy"
expect_failure 'move worker-3 out of app policy before draining: librechat.policy' \
	env CLUSTER_NODE_ASSUME_YES=1 bash "$fixture/ops/configure-cluster-node.sh" state worker-3 draining
sed 's/^NODES=.*/NODES=worker-1,worker-2/' "$fixture/config/cluster/apps/librechat.policy" >"$fixture/librechat.policy"
mv "$fixture/librechat.policy" "$fixture/config/cluster/apps/librechat.policy"

expect_failure 'invalid node state transition: worker-3/active -> retired' \
	env CLUSTER_NODE_ASSUME_YES=1 bash "$fixture/ops/configure-cluster-node.sh" state worker-3 retired
CLUSTER_NODE_ASSUME_YES=1 bash "$fixture/ops/configure-cluster-node.sh" state worker-3 draining >/dev/null
grep -Fxq 'NODE_STATE=draining' "$fixture/config/cluster/nodes/worker-3.env"
CLUSTER_NODE_ASSUME_YES=1 bash "$fixture/ops/configure-cluster-node.sh" state worker-3 retired >/dev/null
grep -Fxq 'NODE_STATE=retired' "$fixture/config/cluster/nodes/worker-3.env"
[[ -f "$fixture/.woodpecker/node-retire-worker-3.yml" ]]
[[ ! -e "$fixture/.woodpecker/foundation-upgrade-worker-3.yml" ]]

printf 'cluster node configuration tests passed\n'
