#!/usr/bin/env bash
set -Eeuo pipefail
umask 077

root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
policy="${CLUSTER_POLICY_FILE:-$root/config/cluster/policy.env}"
output="${WOODPECKER_WORKFLOW_ROOT:-$root/.woodpecker}"
mode="${1:-generate}"
deployment_group='llm-hub-lite-deployment'

value() { sed -n "s/^$1=//p" "$policy" | tail -n1; }
csv_items() { printf '%s\n' "$(value "$1")" | tr ',' '\n' | sed '/^[[:space:]]*$/d'; }
csv_has() {
	local list=",${1//[[:space:]]/},"
	[[ "$list" == *",$2,"* ]]
}
manifest_value() { sed -n "s/^$1=//p" "$2" | tail -n1; }
app_policy_file() { printf '%s/config/%s\n' "$root" "$(manifest_value POLICY_FILE "$1")"; }
app_policy_value() { sed -n "s/^$2=//p" "$(app_policy_file "$1")" 2>/dev/null | tail -n1; }
app_enabled() { [[ "$(app_policy_value "$1" ENABLED)" != false ]]; }
die() {
	printf 'generate-woodpecker-workflows: %s\n' "$*" >&2
	exit 1
}

ids=()
ids_csv=''
while IFS= read -r id; do
	[[ "$id" =~ ^[a-z][a-z0-9-]*$ ]] || die "invalid NODE_ID: $id"
	[[ ",$ids_csv," != *",$id,"* ]] || die "duplicate NODE_ID: $id"
	[[ -f "$root/config/cluster/nodes/$id.env" ]] || die "missing node descriptor: $id"
	[[ "$(sed -n 's/^NODE_ID=//p' "$root/config/cluster/nodes/$id.env" | tail -n1)" == "$id" ]] || die "descriptor NODE_ID mismatch: $id"
	ids+=("$id")
	ids_csv="${ids_csv:+$ids_csv,}$id"
done < <(csv_items NODE_IDS)
((${#ids[@]} > 0)) || die 'NODE_IDS is empty'
migration_id="$(value NEW_API_MIGRATION_NODE_ID)"
backup_id="$(value NEW_API_BACKUP_NODE_ID)"
leader_id="$(value LEADER_NODE_ID)"
repo_slug="$(value REPO_SLUG)"
[[ "$repo_slug" =~ ^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$ ]] || die 'REPO_SLUG must be owner/repository'
[[ ",$ids_csv," == *",$leader_id,"* ]] || die 'LEADER_NODE_ID is not in NODE_IDS'
singleton_apps=()
app_source_paths=''
cluster_policy_paths=''
for manifest in "$root"/apps/*/manifest.env; do
	[[ -f "$manifest" ]] || continue
	placement="$(sed -n 's/^PLACEMENT=//p' "$manifest" | tail -n1)"
	app_id="$(sed -n 's/^APP_ID=//p' "$manifest" | tail -n1)"
	if [[ "$placement" != single-follower ]]; then
		[[ -n "$app_id" ]] || die "application manifest is missing APP_ID: $manifest"
		app_source_paths="${app_source_paths}        - apps/$app_id/**"$'\n'
		policy_rel="$(sed -n 's/^POLICY_FILE=//p' "$manifest" | tail -n1)"
		cluster_policy_paths="${cluster_policy_paths}        - config/$policy_rel"$'\n'
		continue
	fi
	target_key="$(sed -n 's/^TARGET_NODE_KEY=//p' "$manifest" | tail -n1)"
	policy_rel="$(sed -n 's/^POLICY_FILE=//p' "$manifest" | tail -n1)"
	target_id="$(sed -n "s/^$target_key=//p" "$(app_policy_file "$manifest")" | tail -n1)"
	[[ -n "$app_id" && -n "$target_id" ]] || die "singleton manifest is missing APP_ID or target: $manifest"
	[[ ",$ids_csv," == *",$target_id,"* && "$target_id" != "$leader_id" ]] || die "singleton target must be a follower: $app_id"
	singleton_apps+=("$app_id")
done

newapi_enabled=1
app_enabled "$root/apps/newapi/manifest.env" || newapi_enabled=0
if ((newapi_enabled)); then
	[[ ",$ids_csv," == *",$backup_id,"* ]] || die 'NEW_API_BACKUP_NODE_ID is not in NODE_IDS'
	[[ ",$ids_csv," == *",$migration_id,"* ]] || die 'NEW_API_MIGRATION_NODE_ID is not in NODE_IDS'
	[[ "$leader_id" != "$migration_id" ]] || die 'NEW_API_MIGRATION_NODE_ID must be a follower'
	[[ "$(sed -n 's/^NEW_API_NODE_TYPE=//p' "$root/config/cluster/nodes/$migration_id.env" | tail -n1)" == master ]] || die 'migration node must use NEW_API_NODE_TYPE=master'
	master_count=0
	for id in "${ids[@]}"; do
		[[ "$id" == "$leader_id" ]] && continue
		case "$(sed -n 's/^NEW_API_NODE_TYPE=//p' "$root/config/cluster/nodes/$id.env" | tail -n1)" in
		master) master_count=$((master_count + 1)) ;;
		slave) ;;
		*) die "follower $id must set NEW_API_NODE_TYPE to master or slave" ;;
		esac
	done
	((master_count == 1)) || die 'exactly one follower must use NEW_API_NODE_TYPE=master'
fi
ordered=()
ordered+=("$leader_id")
if ((newapi_enabled)); then
	ordered+=("$migration_id")
fi
for id in "${ids[@]}"; do
	[[ "$id" == "${ordered[0]}" || ("$newapi_enabled" -eq 1 && "$id" == "$migration_id") ]] || ordered+=("$id")
done
render() {
	local id="$1" previous="$2" file="$3" event="$4"
	local dep=''
	if [[ -n "$previous" ]]; then
		if [[ "$event" == cluster ]]; then
			dep=$'\ndepends_on:\n  - cluster-reconcile-'"$previous"
		else
			dep=$'\ndepends_on:\n  - deploy-'"$previous"
		fi
	fi
	if [[ "$event" == cluster ]]; then
		cat >"$file" <<EOF
# generated by ops/generate-woodpecker-workflows.sh; do not edit
when:
  - event: push
    branch: main
    path:
      include:
        - config/cluster/policy.env
        - config/cluster/nodes/**
$cluster_policy_paths$dep

labels:
  node: $id
  deployment: "true"
  target: production
  repo: $repo_slug

concurrency:
  limit: 1
  group: $deployment_group

steps:
  reconcile:
    image: llm-hub-lite/deploy-runner:current
    pull: false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/apps/llm-hub-lite:/opt/apps/llm-hub-lite
      - /opt/platform:/opt/platform
      - /opt/backups/llm-hub-lite:/opt/backups/llm-hub-lite
      - /run/lock/llm-hub-lite:/run/lock/llm-hub-lite
      - /etc/llm-hub-lite:/etc/llm-hub-lite
      - /usr/local/bin/platform-submit:/usr/local/bin/platform-submit:ro
    commands:
      - DEPLOY_SKIP_SINGLETONS=1 /usr/local/bin/platform-submit cluster-reconcile "\$CI_COMMIT_SHA"
EOF
	else
		cat >"$file" <<EOF
# generated by ops/generate-woodpecker-workflows.sh; do not edit
when:
  - event: push
    branch: main
    path:
      include:
$app_source_paths        - config/Caddyfile
        - config/foundation-routes.d/**
        - config/routes.d/**

labels:
  node: $id
  deployment: "true"
  target: production
  repo: $repo_slug
$dep
concurrency:
  limit: 1
  group: $deployment_group

steps:
  deploy:
    image: llm-hub-lite/deploy-runner:current
    pull: false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/apps/llm-hub-lite:/opt/apps/llm-hub-lite
      - /opt/platform:/opt/platform
      - /opt/backups/llm-hub-lite:/opt/backups/llm-hub-lite
      - /run/lock/llm-hub-lite:/run/lock/llm-hub-lite
      - /etc/llm-hub-lite:/etc/llm-hub-lite
      - /usr/local/bin/platform-submit:/usr/local/bin/platform-submit:ro
    commands:
      - DEPLOY_SKIP_SINGLETONS=1 /usr/local/bin/platform-submit deploy "\$CI_COMMIT_SHA"
EOF
	fi
}

render_singleton_workflows() {
	local app="$1" manifest target_key target stage_file switch_file previous worker file policy_rel final_worker stop_env
	manifest="$root/apps/$app/manifest.env"
	target_key="$(sed -n 's/^TARGET_NODE_KEY=//p' "$manifest" | tail -n1)"
	target="$(sed -n "s/^$target_key=//p" "$(app_policy_file "$manifest")" | tail -n1)"
	policy_rel="$(sed -n 's/^POLICY_FILE=//p' "$manifest" | tail -n1)"
	stage_file="$output/singleton-stage-$app.yml"
	switch_file="$output/singleton-switch-$app.yml"
	cat >"$stage_file" <<EOF
# generated by ops/generate-woodpecker-workflows.sh; do not edit
when:
  - event: push
    branch: main
    path:
      include:
        - apps/$app/**
        - config/$policy_rel
        - ops/images.apps.prod.env

labels:
  node: $target
  deployment: "true"
  target: production
  repo: $repo_slug

concurrency:
  limit: 1
  group: $deployment_group

steps:
  stage:
    image: llm-hub-lite/deploy-runner:current
    pull: false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/apps/llm-hub-lite:/opt/apps/llm-hub-lite
      - /opt/platform:/opt/platform
      - /opt/backups/llm-hub-lite:/opt/backups/llm-hub-lite
      - /run/lock/llm-hub-lite:/run/lock/llm-hub-lite
      - /etc/llm-hub-lite:/etc/llm-hub-lite
      - /usr/local/bin/platform-submit:/usr/local/bin/platform-submit:ro
    commands:
      - SINGLETON_APP_ID=$app DEPLOY_SKIP_SINGLETONS=0 /usr/local/bin/platform-submit singleton-stage "\$CI_COMMIT_SHA"
EOF
	cat >"$switch_file" <<EOF
# generated by ops/generate-woodpecker-workflows.sh; do not edit
when:
  - event: push
    branch: main
    path:
      include:
        - apps/$app/**
        - config/$policy_rel
        - ops/images.apps.prod.env

depends_on:
  - singleton-stage-$app

labels:
  node: $leader_id
  deployment: "true"
  target: production
  repo: $repo_slug

concurrency:
  limit: 1
  group: $deployment_group

steps:
  switch:
    image: llm-hub-lite/deploy-runner:current
    pull: false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/apps/llm-hub-lite:/opt/apps/llm-hub-lite
      - /opt/platform:/opt/platform
      - /opt/backups/llm-hub-lite:/opt/backups/llm-hub-lite
      - /run/lock/llm-hub-lite:/run/lock/llm-hub-lite
      - /etc/llm-hub-lite:/etc/llm-hub-lite
      - /usr/local/bin/platform-submit:/usr/local/bin/platform-submit:ro
      - /usr/local/bin/platformctl:/usr/local/bin/platformctl:ro
    commands:
      - SINGLETON_APP_ID=$app DEPLOY_SKIP_SINGLETONS=1 /usr/local/bin/platform-submit singleton-switch "\$CI_COMMIT_SHA"
EOF
	previous="singleton-switch-$app"
	final_worker=''
	for worker in "${ids[@]}"; do [[ "$worker" != "$leader_id" ]] && final_worker="$worker"; done
	for worker in "${ids[@]}"; do
		[[ "$worker" != "$leader_id" ]] || continue
		stop_env=""
		[[ "$worker" == "$final_worker" ]] && stop_env=' SINGLETON_FINAL_STOP=1'
		file="$output/singleton-stop-$app-$worker.yml"
		cat >"$file" <<EOF
# generated by ops/generate-woodpecker-workflows.sh; do not edit
when:
  - event: push
    branch: main
    path:
      include:
        - apps/$app/**
        - config/$policy_rel
        - ops/images.apps.prod.env

depends_on:
  - $previous

labels:
  node: $worker
  deployment: "true"
  target: production
  repo: $repo_slug

concurrency:
  limit: 1
  group: $deployment_group

steps:
  stop:
    image: llm-hub-lite/deploy-runner:current
    pull: false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/apps/llm-hub-lite:/opt/apps/llm-hub-lite
      - /opt/platform:/opt/platform
      - /opt/backups/llm-hub-lite:/opt/backups/llm-hub-lite
      - /run/lock/llm-hub-lite:/run/lock/llm-hub-lite
      - /etc/llm-hub-lite:/etc/llm-hub-lite
      - /usr/local/bin/platform-submit:/usr/local/bin/platform-submit:ro
      - /usr/local/bin/platformctl:/usr/local/bin/platformctl:ro
    commands:
      - SINGLETON_APP_ID=$app DEPLOY_SKIP_SINGLETONS=1$stop_env /usr/local/bin/platform-submit singleton-stop "\$CI_COMMIT_SHA"
EOF
		previous="singleton-stop-$app-$worker"
	done
}

render_app_upgrade() {
	local id="$1" file="$2"
	cat >"$file" <<EOF
# generated by ops/generate-woodpecker-workflows.sh; do not edit
when:
  - event: manual
    branch: main

labels:
  node: $id
  deployment: "true"
  target: production
  repo: $repo_slug

concurrency:
  limit: 1
  group: $deployment_group

steps:
  upgrade:
    image: llm-hub-lite/deploy-runner:current
    pull: false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/apps/llm-hub-lite:/opt/apps/llm-hub-lite
      - /opt/platform:/opt/platform
      - /opt/backups/llm-hub-lite:/opt/backups/llm-hub-lite
      - /run/lock/llm-hub-lite:/run/lock/llm-hub-lite
      - /etc/llm-hub-lite:/etc/llm-hub-lite
      - /usr/local/bin/platform-submit:/usr/local/bin/platform-submit:ro
    commands:
      - /usr/local/bin/platform-submit app-upgrade "\$CI_COMMIT_SHA"
EOF
}

render_manual_node() {
	local kind="$1" id="$2" previous="$3" file="$4" command submit_command
	case "$kind" in
	foundation) command="foundation-upgrade \"\$CI_COMMIT_SHA\"" ;;
	runner) command="upgrade-runner" ;;
	rollback) command="rollback \"\${ROLLBACK_TARGET:-previous}\"" ;;
	*) die "unknown manual workflow kind: $kind" ;;
	esac
	submit_command="/usr/local/bin/platform-submit $command"
	[[ "$kind" == runner ]] && submit_command="/usr/local/bin/upgrade-runner"
	cat >"$file" <<EOF
# generated by ops/generate-woodpecker-workflows.sh; do not edit
when:
  - event: manual
    branch: main

EOF
	if [[ -n "$previous" ]]; then
		case "$kind" in
		foundation | runner) printf 'depends_on:\n  - %s-upgrade-%s\n\n' "$kind" "$previous" >>"$file" ;;
		rollback) printf 'depends_on:\n  - rollback-%s\n\n' "$previous" >>"$file" ;;
		*) die "unknown manual workflow kind: $kind" ;;
		esac
	fi
	cat >>"$file" <<EOF
labels:
  node: $id
  deployment: "true"
  target: production
  repo: $repo_slug

concurrency:
  limit: 1
  group: $deployment_group

steps:
  $kind:
    image: llm-hub-lite/deploy-runner:current
    pull: false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/apps/llm-hub-lite:/opt/apps/llm-hub-lite
      - /opt/platform:/opt/platform
      - /opt/backups/llm-hub-lite:/opt/backups/llm-hub-lite
      - /run/lock/llm-hub-lite:/run/lock/llm-hub-lite
      - /etc/llm-hub-lite:/etc/llm-hub-lite
      - /usr/local/bin/platformctl:/usr/local/bin/platformctl:ro
      - /usr/local/bin/platform-submit:/usr/local/bin/platform-submit:ro
      - /usr/local/bin/deploy-controller:/usr/local/bin/deploy-controller:ro
      - /usr/local/bin/git-auth.sh:/usr/local/bin/git-auth.sh:ro
      - /usr/local/bin/backup-platform:/usr/local/bin/backup-platform:ro
      - /usr/local/bin/upgrade-runner:/usr/local/bin/upgrade-runner:ro
    commands:
      - $submit_command
EOF
}

check_dependency_closure() {
	local file dependency
	while IFS= read -r file; do
		while IFS= read -r dependency; do
			[[ -n "$dependency" ]] || continue
			[[ -f "$output/$dependency.yml" ]] || die "workflow dependency does not exist: $file -> $dependency"
		done < <(awk '
      /^depends_on:/ { in_dep=1; next }
      in_dep && /^  - / { sub(/^  - /, ""); print; next }
      in_dep { in_dep=0 }
    ' "$file")
	done < <(find "$output" -maxdepth 1 -type f -name '*.yml' -print | sort)
}

sync_manual_workflows() {
	local file
	for file in "$output"/deploy-*.yml "$output"/cluster-reconcile-*.yml "$output"/app-upgrade-*.yml \
		"$output"/singleton-*.yml "$output"/foundation-upgrade-*.yml "$output"/runner-upgrade-*.yml "$output"/rollback-*.yml "$output/deploy-smoke.yml"; do
		[[ -f "$file" ]] || continue
		head -n1 "$file" | grep -Fq 'generated by ops/generate-woodpecker-workflows.sh' || continue
		rm -f -- "$file"
	done
}

generate() {
	install -d -m 700 "$output"
	sync_manual_workflows
	local id previous='' file
	for id in "${ordered[@]}"; do
		file="$output/deploy-$id.yml"
		render "$id" "$previous" "$file" deploy
		previous="$id"
	done
	local cluster_previous=''
	for id in "${ids[@]}"; do
		render "$id" "$cluster_previous" "$output/cluster-reconcile-$id.yml" cluster
		cluster_previous="$id"
		[[ "$id" == "$leader_id" ]] || render_app_upgrade "$id" "$output/app-upgrade-$id.yml"
	done
	for app in "${singleton_apps[@]}"; do render_singleton_workflows "$app"; done
	{
		printf '%s\n' '# generated by ops/generate-woodpecker-workflows.sh; do not edit'
		printf '%s\n' 'when:' '  - event: push' '    branch: main' '    path:' '      include:'
		printf '%s' "$app_source_paths"
		printf '%s\n' '        - config/Caddyfile' '        - config/foundation-routes.d/**' '        - config/routes.d/**' '' 'depends_on:'
		for id in "${ordered[@]}"; do printf '  - deploy-%s\n' "$id"; done
		printf '%s\n' '' 'labels:' "  node: $leader_id" '  deployment: "true"' '  target: production' "  repo: $repo_slug" '' 'concurrency:' '  limit: 1' "  group: $deployment_group" '' 'steps:' '  smoke:' '    image: llm-hub-lite/deploy-runner:current' '    pull: false' '    volumes:' '      - /var/run/docker.sock:/var/run/docker.sock' '      - /opt/apps/llm-hub-lite:/opt/apps/llm-hub-lite' '      - /opt/platform:/opt/platform' '      - /opt/backups/llm-hub-lite:/opt/backups/llm-hub-lite' '      - /run/lock/llm-hub-lite:/run/lock/llm-hub-lite' '      - /etc/llm-hub-lite:/etc/llm-hub-lite' '      - /usr/local/bin/platformctl:/usr/local/bin/platformctl:ro' '    commands:' '      - /usr/local/bin/platformctl health' '      - /usr/local/bin/platformctl smoke all'
	} >"$output/deploy-smoke.yml"
	local previous=''
	for id in "${ordered[@]}"; do
		render_manual_node foundation "$id" "$previous" "$output/foundation-upgrade-$id.yml"
		render_manual_node runner "$id" "$previous" "$output/runner-upgrade-$id.yml"
		previous="$id"
	done
	previous=''
	for id in "${ordered[@]}"; do
		[[ "$id" == "$leader_id" ]] || continue
		for worker in "${ids[@]}"; do [[ "$worker" != "$leader_id" ]] && render_manual_node rollback "$worker" "$previous" "$output/rollback-$worker.yml" && previous="$worker"; done
		render_manual_node rollback "$leader_id" "$previous" "$output/rollback-$leader_id.yml"
	done
	check_dependency_closure
}

check_manual_workflows() {
	local file
	for file in "$output"/foundation-upgrade-*.yml "$output"/runner-upgrade-*.yml "$output"/rollback-*.yml; do
		[[ -f "$file" ]] || die "missing manual workflow: $file"
		grep -Fqx "  repo: $repo_slug" "$file" || die "manual workflow has stale repo label: $file"
	done
	while IFS= read -r file; do
		[[ -f "$file" ]] || continue
		if head -n1 "$file" | grep -Fq 'generated by ops/generate-woodpecker-workflows.sh'; then
			[[ -f "$tmp/$(basename "$file")" ]] || die "stale generated workflow: $file"
		fi
	done < <(find "$output" -mindepth 1 -maxdepth 1 -type f -name '*.yml' -print | sort)
}

case "$mode" in
generate) generate ;;
--check)
	tmp="$(mktemp -d)"
	trap 'rm -rf -- "$tmp"' EXIT
	real_output="$output"
	output="$tmp"
	generate
	output="$real_output"
	for file in "$tmp"/*.yml; do
		target="$output/$(basename "$file")"
		cmp -s "$file" "$target" || die "workflow is stale or differs: $target"
	done
	for file in "$output"/deploy-*.yml "$output"/cluster-reconcile-*.yml "$output"/app-upgrade-*.yml "$output"/singleton-*.yml; do
		[[ -f "$file" ]] || continue
		[[ -f "$tmp/$(basename "$file")" ]] || die "stale generated workflow: $file"
	done
	check_manual_workflows
	;;
*) die 'usage: generate-woodpecker-workflows.sh [generate|--check]' ;;
esac
