#!/usr/bin/env bash
# shellcheck disable=SC2016,SC2129
# SC2016: Woodpecker variables must stay literal in generated YAML.
# SC2129: workflow files are assembled from successive heredocs and
# write_volumes output, so they are appended redirect-by-redirect.
set -Eeuo pipefail
umask 077

root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
policy="${CLUSTER_POLICY_FILE:-$root/config/cluster/policy.env}"
output="${WOODPECKER_WORKFLOW_ROOT:-$root/.woodpecker}"
lock_output_root="$root/apps"
mode="${1:-generate}"
deployment_group='llm-hub-lite-deployment'

env_value() {
	local key="$1" file="$2" line value=''
	[[ -f "$file" ]] || return 0
	while IFS= read -r line || [[ -n "$line" ]]; do
		[[ "$line" == "$key="* ]] || continue
		value="${line#*=}"
	done <"$file"
	printf '%s\n' "$value"
}
value() { env_value "$1" "$policy"; }
deploy_debug_level="${DEPLOY_DEBUG_LEVEL:-$(value DEPLOY_DEBUG_LEVEL)}"
deploy_debug_level="${deploy_debug_level:-off}"
case "$deploy_debug_level" in off | warn | debug) ;; *) die 'DEPLOY_DEBUG_LEVEL must be off, warn, or debug' ;; esac
csv_has() {
	local csv=",${1//[[:space:]]/},"
	[[ "$csv" == *",$2,"* ]]
}
die() {
	printf 'generate-woodpecker-workflows: %s\n' "$*" >&2
	exit 1
}
app_policy_file() {
	local manifest="$1" app rel
	app="$(env_value APP_ID "$manifest")"
	rel="$(env_value POLICY_FILE "$manifest")"
	[[ "$rel" == "cluster/apps/$app.policy" ]] || die "invalid app policy path: $manifest"
	printf '%s/config/%s\n' "$root" "$rel"
}
render_image_lock() {
	local manifest="$1" app destination key image
	app="$(env_value APP_ID "$manifest")"
	destination="$lock_output_root/$app/images.lock.env"
	install -d -m 700 "$(dirname "$destination")"
	{
		printf '# generated by ops/generate-woodpecker-workflows.sh; do not edit\n'
		for key in $(env_value IMAGE_KEYS "$manifest"); do
			[[ "$key" =~ ^[A-Z][A-Z0-9_]*$ ]] || die "invalid IMAGE_KEYS entry: $manifest/$key"
			image="$(env_value "$key" "$root/ops/images.apps.prod.env")"
			[[ "$image" =~ @sha256:[0-9a-f]{64}$ ]] || die "application image is missing or not digest-pinned: $app/$key"
			printf '%s=%s\n' "$key" "$image"
		done
	} >"$destination"
}

ids=()
followers=()
active_ids=()
reconcile_ids=()
consumer_nodes=()
active_consumer_nodes=()
retired_ids=()
ids_csv=''
while IFS= read -r id; do
	[[ -n "$id" ]] || continue
	[[ "$id" =~ ^[a-z][a-z0-9-]*$ ]] || die "invalid NODE_ID: $id"
	! csv_has "$ids_csv" "$id" || die "duplicate NODE_ID: $id"
	[[ -f "$root/config/cluster/nodes/$id.env" ]] || die "missing node descriptor: $id"
	[[ "$(env_value NODE_ID "$root/config/cluster/nodes/$id.env")" == "$id" ]] || die "descriptor NODE_ID mismatch: $id"
	state="$(env_value NODE_STATE "$root/config/cluster/nodes/$id.env")"
	case "$state" in
	joining) ;;
	draining) reconcile_ids+=("$id") ;;
	active)
		active_ids+=("$id")
		reconcile_ids+=("$id")
		;;
	retired) retired_ids+=("$id") ;;
	*) die "NODE_STATE must be joining, active, draining, or retired: $id" ;;
	esac
	ids+=("$id")
	ids_csv="${ids_csv:+$ids_csv,}$id"
done < <(printf '%s\n' "$(value NODE_IDS)" | tr ',' '\n')
((${#ids[@]} > 0)) || die 'NODE_IDS is empty'
leader_id="$(value LEADER_NODE_ID)"
repo_slug="$(value REPO_SLUG)"
[[ "$repo_slug" =~ ^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$ ]] || die 'REPO_SLUG must be owner/repository'
csv_has "$ids_csv" "$leader_id" || die 'LEADER_NODE_ID is not in NODE_IDS'
[[ "$(env_value NODE_STATE "$root/config/cluster/nodes/$leader_id.env")" == active ]] || die "designated Leader node must be active: $leader_id"
for id in "${ids[@]}"; do
	[[ "$id" == "$leader_id" ]] && continue
	followers+=("$id")
	state="$(env_value NODE_STATE "$root/config/cluster/nodes/$id.env")"
	[[ "$state" == active || "$state" == draining ]] && consumer_nodes+=("$id")
	[[ "$state" == active ]] && active_consumer_nodes+=("$id")
done
((${#followers[@]} > 0)) || die 'at least one follower is required for consumer placement'

write_volumes() {
	cat <<'EOF'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/apps/llm-hub-lite:/opt/apps/llm-hub-lite
      - /opt/platform:/opt/platform
      - /opt/backups/llm-hub-lite:/opt/backups/llm-hub-lite
      - /run/lock/llm-hub-lite:/run/lock/llm-hub-lite
      - /etc/llm-hub-lite:/etc/llm-hub-lite
      - /usr/local/bin/platform-submit:/usr/local/bin/platform-submit:ro
      - /usr/local/bin/platformctl:/usr/local/bin/platformctl:ro
      - /usr/local/bin/configure-app-secrets:/usr/local/bin/configure-app-secrets:ro
EOF
}

write_consumer_header() {
	local file="$1" app="$2" node="$3" dependency="$4"
	cat >"$file" <<EOF
# generated by ops/generate-woodpecker-workflows.sh; do not edit
skip_clone: true
when:
  - event: push
    branch: main
    path:
      include:
        - apps/$app/**
        - config/cluster/apps/$app.policy
        - config/cluster/overrides/**/$app.env
        - apps/$app/route*.caddy
        - apps/$app/images.lock.env
      on_empty: false
EOF
	printf '\ndepends_on:\n' >>"$file"
	[[ -n "$dependency" ]] && printf '  - %s\n' "$dependency" >>"$file"
	printf '  - control-sync-%s\n' "$node" >>"$file"
	printf '  - name: foundation-reconcile-%s\n    optional: true\n' "$node" >>"$file"
	printf '  - name: cluster-reconcile-%s\n    optional: true\n' "$node" >>"$file"
	cat >>"$file" <<EOF

labels:
  node: $node
  deployment: "true"
  target: production
  repo: $repo_slug

concurrency:
  limit: 1
  group: $deployment_group

steps:
EOF
}

render_control_sync() {
	local id dependency file
	id="$1"
	dependency="$2"
	file="$output/control-sync-$id.yml"
	cat >"$file" <<EOF
# generated by ops/generate-woodpecker-workflows.sh; do not edit
skip_clone: true
when:
  - event: push
    branch: main

EOF
	if [[ -n "$dependency" ]]; then
		printf 'depends_on:\n  - %s\n\n' "$dependency" >>"$file"
	fi
	cat >>"$file" <<EOF
labels:
  node: $id
  deployment: "true"
  target: production
  repo: $repo_slug

concurrency:
  limit: 1
  group: $deployment_group

steps:
  control-sync:
    image: llm-hub-lite/deploy-runner:current
    pull: false
EOF
	write_volumes >>"$file"
	cat >>"$file" <<EOF
    commands:
      - DEPLOY_DEBUG_LEVEL=$deploy_debug_level /usr/local/bin/platform-submit control-sync "\$CI_COMMIT_SHA"
EOF
}

render_cluster_reconcile() {
	local id="$1" dependency="$2" file
	file="$output/cluster-reconcile-$id.yml"
	cat >"$file" <<EOF
# generated by ops/generate-woodpecker-workflows.sh; do not edit
skip_clone: true
when:
  - event: push
    branch: main
    path:
      include:
        - config/cluster/policy.env
        - config/cluster/nodes/**
        - config/cluster/foundation/**
      on_empty: false

EOF
	if [[ -n "$dependency" ]]; then
		printf 'depends_on:\n  - %s\n  - control-sync-%s\n\n' "$dependency" "$id" >>"$file"
	else
		printf 'depends_on:\n  - control-sync-%s\n\n' "$id" >>"$file"
	fi
	cat >>"$file" <<EOF
labels:
  node: $id
  deployment: "true"
  target: production
  repo: $repo_slug

concurrency:
  limit: 1
  group: $deployment_group

steps:
  reconcile:
    image: llm-hub-lite/deploy-runner:current
    pull: false
EOF
	write_volumes >>"$file"
	cat >>"$file" <<EOF
    commands:
      - DEPLOY_DEBUG_LEVEL=$deploy_debug_level /usr/local/bin/platform-submit cluster-reconcile "\$CI_COMMIT_SHA"
EOF
}

render_foundation_reconcile() {
	local id="$1" dependency="${2:-}" file
	file="$output/foundation-reconcile-$id.yml"
	cat >"$file" <<EOF
# generated by ops/generate-woodpecker-workflows.sh; do not edit
skip_clone: true
when:
  - event: push
    branch: main
    path:
      include:
        - compose/foundation/**
        - config/Caddyfile
        - config/foundation-routes.d/**
        - config/cluster/foundation/**
        - ops/foundation/**
        - ops/images.foundation.prod.env
      on_empty: false

depends_on:
  - control-sync-$id
EOF
	if [[ -n "$dependency" ]]; then
		printf '  - name: %s\n    optional: true\n' "$dependency" >>"$file"
	fi
	cat >>"$file" <<EOF

labels:
  node: $id
  deployment: "true"
  target: production
  repo: $repo_slug

concurrency:
  limit: 1
  group: $deployment_group

steps:
  foundation:
    image: llm-hub-lite/deploy-runner:current
    pull: false
EOF
	write_volumes >>"$file"
	cat >>"$file" <<EOF
    commands:
      - DEPLOY_DEBUG_LEVEL=$deploy_debug_level /usr/local/bin/platform-submit foundation-upgrade "\$CI_COMMIT_SHA"
EOF
}

render_push_audit() {
	local file="$output/push-audit.yml"
	cat >"$file" <<EOF
# generated by ops/generate-woodpecker-workflows.sh; do not edit
# This workflow intentionally has no path filter.  It makes every main push
# visible in Woodpecker, including pushes that do not select a deployment job.
skip_clone: true
when:
  - event: push
    branch: main

labels:
  node: $leader_id
  target: production
  repo: $repo_slug

concurrency:
  limit: 1
  group: llm-hub-lite-push-audit

steps:
  audit:
    image: llm-hub-lite/deploy-runner:current
    pull: false
EOF
	write_volumes >>"$file"
	cat >>"$file" <<EOF
    commands:
      - printf 'Woodpecker push received sha=%s ref=%s repo=%s\\n' "\$CI_COMMIT_SHA" "\$CI_COMMIT_REF" "\$CI_REPO"
      - printf 'Changed paths (deployment workflows are selected independently):\\n'
      - git --git-dir=/opt/platform/control/mirror.git show --format= --name-only "\$CI_COMMIT_SHA" | sed '/^\$/d'
EOF
}

render_consumer_secrets() {
	local app="$1" node="$2" dependency="$3" keys="$4" file key secret_name target_arg='' workflow_name
	file="$output/consumer-secrets-$app-$node.yml"
	workflow_name="consumer-secrets-$app-$node"
	[[ "$node" == "$leader_id" ]] || target_arg=" --target-node $node"
	cat >"$file" <<EOF
# generated by ops/generate-woodpecker-workflows.sh; do not edit
when:
  - event: manual
    branch: main
    evaluate: 'MANUAL_WORKFLOW == "$workflow_name"'
EOF
	if [[ -n "$dependency" ]]; then
		printf '\ndepends_on:\n  - %s\n' "$dependency" >>"$file"
	fi
	cat >>"$file" <<EOF

labels:
  node: $node
  deployment: "true"
  target: production
  repo: $repo_slug

concurrency:
  limit: 1
  group: $deployment_group

steps:
  secrets:
    image: llm-hub-lite/deploy-runner:current
    pull: false
EOF
	write_volumes >>"$file"
	printf '    environment:\n' >>"$file"
	while IFS= read -r key; do
		[[ -n "$key" ]] || continue
		secret_name="$(woodpecker_secret_name "$app" "$key")"
		printf '      %s:\n        from_secret: %s\n' "$key" "$secret_name" >>"$file"
	done < <(printf '%s\n' "$keys" | tr ',' '\n')
	cat >>"$file" <<EOF
    commands:
      - /usr/local/bin/configure-app-secrets $app$target_arg --non-interactive
EOF
}
woodpecker_secret_name() {
	local app="$1" wanted="$2" manifest rule key name
	manifest="$root/apps/$app/manifest.env"
	while IFS= read -r rule; do
		[[ -n "$rule" ]] || continue
		key="${rule%%:*}"
		name="${rule#*:}"
		[[ "$key" =~ ^[A-Z][A-Z0-9_]*$ && "$name" =~ ^[A-Za-z_][A-Za-z0-9_-]*$ ]] ||
			die "invalid WOODPECKER_SECRET_NAMES entry: $app/$rule"
		if [[ "$key" == "$wanted" ]]; then
			printf '%s\n' "$name"
			return 0
		fi
	done < <(printf '%s\n' "$(env_value WOODPECKER_SECRET_NAMES "$manifest")" | tr ',' '\n')
	printf '%s' "$wanted" | tr '[:upper:]' '[:lower:]'
}
conditional_secret_keys() {
	local manifest="$1" node="${2:-}" rule selector expected keys config_file override_file value result=''
	config_file="$(dirname "$manifest")/$(env_value CONFIG_FILE "$manifest")"
	override_file="$root/config/cluster/overrides/$node/$(env_value APP_ID "$manifest").env"
	while IFS= read -r rule; do
		[[ -n "$rule" ]] || continue
		selector="${rule%%=*}"
		expected="${rule#*=}"
		keys="${expected#*|}"
		expected="${expected%%|*}"
		value="$(env_value "$selector" "$override_file")"
		[[ -n "$value" ]] || value="$(env_value "$selector" "$config_file")"
		[[ "$value" == "$expected" ]] || continue
		result="${result:+$result,}$keys"
	done < <(printf '%s\n' "$(env_value CONDITIONAL_SECRET_KEYS "$manifest")" | tr ';' '\n')
	printf '%s\n' "$result"
}

render_consumer_stage() {
	local app="$1" node="$2" dependency="$3" file
	file="$output/consumer-stage-$app-$node.yml"
	write_consumer_header "$file" "$app" "$node" "$dependency"
	cat >>"$file" <<EOF
  stage:
    image: llm-hub-lite/deploy-runner:current
    pull: false
EOF
	write_volumes >>"$file"
	cat >>"$file" <<EOF
    commands:
      - DEPLOY_DEBUG_LEVEL=$deploy_debug_level CONSUMER_APP_ID=$app /usr/local/bin/platform-submit consumer-stage "\$CI_COMMIT_SHA"
EOF
}

render_consumer_publish() {
	local app="$1" dependency="$2" file
	file="$output/consumer-publish-$app.yml"
	write_consumer_header "$file" "$app" "$leader_id" "$dependency"
	cat >>"$file" <<EOF
  publish:
    image: llm-hub-lite/deploy-runner:current
    pull: false
EOF
	write_volumes >>"$file"
	cat >>"$file" <<EOF
    commands:
      - DEPLOY_DEBUG_LEVEL=$deploy_debug_level CONSUMER_APP_ID=$app /usr/local/bin/platform-submit consumer-publish "\$CI_COMMIT_SHA"
EOF
}

render_consumer_stop() {
	local app="$1" node="$2" dependency="$3" file
	file="$output/consumer-stop-$app-$node.yml"
	write_consumer_header "$file" "$app" "$node" "$dependency"
	cat >>"$file" <<EOF
  stop:
    image: llm-hub-lite/deploy-runner:current
    pull: false
EOF
	write_volumes >>"$file"
	cat >>"$file" <<EOF
    commands:
      - DEPLOY_DEBUG_LEVEL=$deploy_debug_level CONSUMER_APP_ID=$app /usr/local/bin/platform-submit consumer-stop "\$CI_COMMIT_SHA"
EOF
}

render_consumer_finalize() {
	local app="$1" node="$2" dependency="$3" file
	file="$output/consumer-finalize-$app-$node.yml"
	write_consumer_header "$file" "$app" "$node" "$dependency"
	cat >>"$file" <<EOF
  finalize:
    image: llm-hub-lite/deploy-runner:current
    pull: false
EOF
	write_volumes >>"$file"
	cat >>"$file" <<EOF
    commands:
      - DEPLOY_DEBUG_LEVEL=$deploy_debug_level SINGLETON_FINAL_STOP=1 CONSUMER_APP_ID=$app /usr/local/bin/platform-submit consumer-stop "\$CI_COMMIT_SHA"
EOF
}

render_consumer_workflows() {
	local manifest="$1" app placement upstream policy_file enabled nodes node previous='' publish_name seen='' count=0 undesired='' primary_key primary target cluster_keys node_keys conditional_keys secret_keys
	app="$(env_value APP_ID "$manifest")"
	placement="$(env_value PLACEMENT "$manifest")"
	upstream="$(env_value UPSTREAM_MODE "$manifest")"
	[[ "$app" == "$(basename "$(dirname "$manifest")")" && "$app" =~ ^[a-z][a-z0-9-]*$ ]] || die "invalid APP_ID: $manifest"
	[[ "$(env_value MANIFEST_VERSION "$manifest")" == 5 ]] || die "unsupported application manifest version: $manifest"
	[[ "$placement" == consumer ]] || die "application placement must be consumer: $manifest"
	policy_file="$(app_policy_file "$manifest")"
	[[ -f "$policy_file" ]] || die "missing app policy: $app"
	enabled="$(env_value ENABLED "$policy_file")"
	case "$enabled" in true | false) ;; *) die "app policy ENABLED must be true or false: $app" ;; esac
	nodes="$(env_value NODES "$policy_file")"
	[[ -n "$nodes" ]] || die "application policy NODES is empty: $app"
	while IFS= read -r node; do
		[[ "$node" =~ ^[a-z][a-z0-9-]*$ ]] || die "invalid consumer node: $app/$node"
		csv_has "$ids_csv" "$node" || die "consumer node is absent from NODE_IDS: $app/$node"
		[[ "$node" != "$leader_id" ]] || die "consumer node must be an active follower: $app/$node"
		if [[ "$enabled" == true ]]; then
			[[ "$(env_value NODE_STATE "$root/config/cluster/nodes/$node.env")" == active ]] || die "consumer node must be an active follower: $app/$node"
		fi
		! csv_has "$seen" "$node" || die "duplicate consumer node: $app/$node"
		seen="${seen:+$seen,}$node"
		count=$((count + 1))
	done < <(printf '%s\n' "$nodes" | tr ',' '\n')
	case "$upstream" in
	singleton) ((count == 1)) || die "singleton application must target exactly one follower: $app" ;;
	active-active) ((count >= 1)) || die "$upstream application requires a follower: $app" ;;
	active-passive)
		((count >= 1)) || die "$upstream application requires a follower: $app"
		primary_key="$(env_value PRIMARY_NODE_KEY "$manifest")"
		[[ "$primary_key" =~ ^[A-Z][A-Z0-9_]*$ ]] || die "active-passive application requires PRIMARY_NODE_KEY: $app"
		primary="$(env_value "$primary_key" "$policy_file")"
		csv_has "$nodes" "$primary" || die "active-passive primary is absent from NODES: $app/$primary"
		;;
	*) die "unsupported UPSTREAM_MODE for $app: $upstream" ;;
	esac
	if [[ "$app" == newapi && "$enabled" == true ]]; then
		for primary_key in NEW_API_MIGRATION_NODE_ID NEW_API_BACKUP_NODE_ID; do
			primary="$(env_value "$primary_key" "$policy_file")"
			csv_has "$nodes" "$primary" || die "$primary_key is absent from New API NODES: $primary"
		done
	fi
	if [[ "$enabled" == true ]]; then
		while IFS= read -r node; do
			render_consumer_stage "$app" "$node" "$previous"
			previous="consumer-stage-$app-$node"
		done < <(printf '%s\n' "$nodes" | tr ',' '\n')
	fi
	render_consumer_publish "$app" "$previous"
	publish_name="consumer-publish-$app"
	for node in "${consumer_nodes[@]}"; do
		if [[ "$enabled" != true ]] || ! csv_has "$nodes" "$node"; then
			undesired="${undesired}${node}"$'\n'
		fi
	done
	previous="$publish_name"
	while IFS= read -r node; do
		[[ -n "$node" ]] || continue
		render_consumer_stop "$app" "$node" "$previous"
		previous="consumer-stop-$app-$node"
	done <<<"$undesired"
	if [[ "$enabled" == true && "$upstream" == singleton ]]; then
		target="${nodes%%,*}"
		render_consumer_finalize "$app" "$target" "$previous"
	fi
	if [[ "$enabled" == true ]]; then
		cluster_keys="$(env_value CLUSTER_SECRET_KEYS "$manifest")"
		node_keys="$(env_value NODE_SECRET_KEYS "$manifest")"
		conditional_keys="$(conditional_secret_keys "$manifest" "$leader_id")"
		if [[ -n "$cluster_keys" || -n "$conditional_keys" ]]; then
			render_consumer_secrets "$app" "$leader_id" '' "$cluster_keys,$conditional_keys"
		fi
		# Node-local secrets belong only on the nodes selected by this app's
		# placement policy.  Cleanup workflows above still cover active nodes
		# removed from placement, but they must not receive new credentials.
		while IFS= read -r node; do
			[[ -n "$node" ]] || continue
			conditional_keys="$(conditional_secret_keys "$manifest" "$node")"
			secret_keys="$cluster_keys,$conditional_keys"
			[[ -z "$node_keys" ]] || secret_keys="${secret_keys:+$secret_keys,}$node_keys"
			[[ -n "$secret_keys" ]] || continue
			render_consumer_secrets "$app" "$node" '' "$secret_keys"
		done < <(printf '%s\n' "$nodes" | tr ',' '\n')
	fi
}

render_manual_node() {
	local kind="$1" id="$2" previous="$3" file="$4" command submit workflow_name
	workflow_name="${file##*/}"
	workflow_name="${workflow_name%.yml}"
	case "$kind" in
	foundation) command='foundation-upgrade "$CI_COMMIT_SHA"' ;;
	runner) command='upgrade-runner' ;;
	rollback) command='rollback "${ROLLBACK_TARGET:-previous}"' ;;
	retire) command='node-retire "$CI_COMMIT_SHA"' ;;
	*) die "unknown manual workflow kind: $kind" ;;
	esac
	submit="/usr/local/bin/platform-submit $command"
	[[ "$kind" == runner ]] && submit='/usr/local/bin/upgrade-runner'
	cat >"$file" <<EOF
# generated by ops/generate-woodpecker-workflows.sh; do not edit
when:
  - event: manual
    branch: main
    evaluate: 'MANUAL_WORKFLOW == "$workflow_name"'
EOF
	[[ -z "$previous" ]] || printf '\ndepends_on:\n  - %s\n' "$previous" >>"$file"
	cat >>"$file" <<EOF

labels:
  node: $id
  deployment: "true"
  target: production
  repo: $repo_slug

concurrency:
  limit: 1
  group: $deployment_group

steps:
  $kind:
    image: llm-hub-lite/deploy-runner:current
    pull: false
EOF
	write_volumes >>"$file"
	cat >>"$file" <<EOF
      - /usr/local/bin/deploy-controller:/usr/local/bin/deploy-controller:ro
      - /usr/local/bin/git-auth.sh:/usr/local/bin/git-auth.sh:ro
      - /usr/local/bin/backup-platform:/usr/local/bin/backup-platform:ro
      - /usr/local/bin/upgrade-runner:/usr/local/bin/upgrade-runner:ro
    commands:
      - $submit
EOF
}

remove_generated() {
	local file
	for file in "$output"/*.yml; do
		[[ -f "$file" ]] || continue
		head -n1 "$file" | grep -Fq 'generated by ops/generate-woodpecker-workflows.sh' || continue
		rm -f -- "$file"
	done
	for file in "$lock_output_root"/*/images.lock.env; do
		[[ -f "$file" ]] || continue
		head -n1 "$file" | grep -Fq 'generated by ops/generate-woodpecker-workflows.sh' || continue
		rm -f -- "$file"
	done
}
check_dependency_closure() {
	local file dependency
	for file in "$output"/*.yml; do
		[[ -f "$file" ]] || continue
		while IFS= read -r dependency; do
			[[ -n "$dependency" ]] || continue
			[[ -f "$output/$dependency.yml" ]] || die "workflow dependency does not exist: $file -> $dependency"
		done < <(awk '/^depends_on:/ {active=1; next} active && /^  - name: / {sub(/^  - name: /, ""); print; next} active && /^  - / {sub(/^  - /, ""); print; next} active {active=0}' "$file")
	done
}
render_all() {
	local manifest id previous
	install -d -m 700 "$output"
	previous=''
	for id in "${ids[@]}"; do
		render_control_sync "$id" "$previous"
		previous="control-sync-$id"
	done
	render_push_audit
	previous=''
	for id in "${reconcile_ids[@]}"; do
		render_foundation_reconcile "$id" "$previous"
		previous="foundation-reconcile-$id"
	done
	for manifest in "$root"/apps/*/manifest.env; do
		[[ -f "$manifest" ]] || continue
		render_image_lock "$manifest"
		render_consumer_workflows "$manifest"
	done
	previous=''
	render_cluster_reconcile "$leader_id" "$previous"
	previous="cluster-reconcile-$leader_id"
	for id in "${reconcile_ids[@]}"; do
		[[ "$id" == "$leader_id" ]] && continue
		render_cluster_reconcile "$id" "$previous"
		previous="cluster-reconcile-$id"
	done
	previous=''
	render_manual_node foundation "$leader_id" "$previous" "$output/foundation-upgrade-$leader_id.yml"
	previous="foundation-upgrade-$leader_id"
	for id in "${active_ids[@]}"; do
		[[ "$id" == "$leader_id" ]] && continue
		render_manual_node foundation "$id" "$previous" "$output/foundation-upgrade-$id.yml"
		previous="foundation-upgrade-$id"
	done
	previous=''
	render_manual_node runner "$leader_id" "$previous" "$output/runner-upgrade-$leader_id.yml"
	previous="runner-upgrade-$leader_id"
	for id in "${active_ids[@]}"; do
		[[ "$id" == "$leader_id" ]] && continue
		render_manual_node runner "$id" "$previous" "$output/runner-upgrade-$id.yml"
		previous="runner-upgrade-$id"
	done
	previous=''
	for id in "${consumer_nodes[@]}"; do
		render_manual_node rollback "$id" "$previous" "$output/rollback-$id.yml"
		previous="rollback-$id"
	done
	render_manual_node rollback "$leader_id" "$previous" "$output/rollback-$leader_id.yml"
	# Bash 3.2 treats an empty array expansion as unbound under `set -u`.
	# The default cluster has no retired nodes, so tolerate the one empty item.
	for id in "${retired_ids[@]-}"; do
		[[ -n "$id" ]] || continue
		render_manual_node retire "$id" '' "$output/node-retire-$id.yml"
	done
	check_dependency_closure
}

copy_generated_stage() {
	local stage="$1" file target
	for file in "$stage"/*.yml; do
		[[ -f "$file" ]] || continue
		target="$output/$(basename "$file")"
		if ! cp -p "$file" "$target"; then return 1; fi
	done
	for file in "$stage"/apps/*/images.lock.env; do
		[[ -f "$file" ]] || continue
		target="$lock_output_root/$(basename "$(dirname "$file")")/images.lock.env"
		install -d -m 700 "$(dirname "$target")"
		if ! cp -p "$file" "$target"; then return 1; fi
	done
}

generate_transaction() {
	local stage backup real_output real_lock_output_root file relative
	install -d -m 700 "$output" "$lock_output_root"
	stage="$(mktemp -d "${output}.staging.XXXXXX")"
	real_output="$output"
	real_lock_output_root="$lock_output_root"
	output="$stage"
	lock_output_root="$stage/apps"
	if ! render_all; then
		output="$real_output"
		lock_output_root="$real_lock_output_root"
		rm -rf -- "$stage"
		return 1
	fi
	output="$real_output"
	lock_output_root="$real_lock_output_root"
	# Render and dependency validation have succeeded. Keep a private copy of
	# every generated artifact so an interrupted apply can restore it exactly.
	backup="$(mktemp -d "${output}.backup.XXXXXX")"
	for file in "$output"/*.yml; do
		[[ -f "$file" ]] || continue
		head -n1 "$file" | grep -Fq 'generated by ops/generate-woodpecker-workflows.sh' || continue
		cp -p "$file" "$backup/$(basename "$file")" || {
			rm -rf -- "$stage" "$backup"
			return 1
		}
	done
	for file in "$lock_output_root"/*/images.lock.env; do
		[[ -f "$file" ]] || continue
		head -n1 "$file" | grep -Fq 'generated by ops/generate-woodpecker-workflows.sh' || continue
		relative="apps/$(basename "$(dirname "$file")")/images.lock.env"
		install -d -m 700 "$backup/apps/$(basename "$(dirname "$file")")"
		cp -p "$file" "$backup/$relative" || {
			rm -rf -- "$stage" "$backup"
			return 1
		}
	done
	if ! remove_generated || ! copy_generated_stage "$stage"; then
		# Best-effort rollback is deliberately explicit. The old set is restored
		# before the caller reports failure, so a partial workflow set is never
		# left for Woodpecker to execute.
		remove_generated || true
		for file in "$backup"/*.yml; do
			[[ -f "$file" ]] || continue
			cp -p "$file" "$output/$(basename "$file")" || true
		done
		for file in "$backup"/apps/*/images.lock.env; do
			[[ -f "$file" ]] || continue
			target="$lock_output_root/$(basename "$(dirname "$file")")/images.lock.env"
			install -d -m 700 "$(dirname "$target")"
			cp -p "$file" "$target" || true
		done
		rm -rf -- "$stage" "$backup"
		return 1
	fi
	rm -rf -- "$stage" "$backup"
}

case "$mode" in
generate) generate_transaction || die 'unable to apply generated workflow set atomically' ;;
--check)
	tmp="$(mktemp -d)"
	trap 'rm -rf -- "$tmp"' EXIT
	real_output="$output"
	real_lock_output_root="$lock_output_root"
	output="$tmp"
	lock_output_root="$tmp/apps"
	render_all
	output="$real_output"
	lock_output_root="$real_lock_output_root"
	for file in "$tmp"/*.yml; do
		target="$output/$(basename "$file")"
		cmp -s "$file" "$target" || die "workflow is stale or differs: $target"
	done
	for file in "$tmp"/apps/*/images.lock.env; do
		[[ -f "$file" ]] || continue
		app="$(basename "$(dirname "$file")")"
		target="$lock_output_root/$app/images.lock.env"
		cmp -s "$file" "$target" || die "application image lock is stale or differs: $target"
	done
	for file in "$output"/*.yml; do
		[[ -f "$file" ]] || continue
		if head -n1 "$file" | grep -Fq 'generated by ops/generate-woodpecker-workflows.sh'; then
			[[ -f "$tmp/$(basename "$file")" ]] || die "stale generated workflow: $file"
		fi
	done
	check_dependency_closure
	;;
*) die 'usage: generate-woodpecker-workflows.sh [generate|--check]' ;;
esac
