#!/usr/bin/env bash
# shellcheck disable=SC2016,SC2129
# SC2016: Woodpecker variables must stay literal in generated YAML.
# SC2129: workflow files are assembled from successive heredocs and
# write_volumes output, so they are appended redirect-by-redirect.
set -Eeuo pipefail
umask 077

root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
policy="${CLUSTER_POLICY_FILE:-$root/config/cluster/policy.env}"
output="${WOODPECKER_WORKFLOW_ROOT:-$root/.woodpecker}"
lock_output_root="$root/apps"
mode="${1:-generate}"
deployment_group_prefix='llm-hub-lite-node'

env_value() {
	local key="$1" file="$2" line value=''
	[[ -f "$file" ]] || return 0
	while IFS= read -r line || [[ -n "$line" ]]; do
		[[ "$line" == "$key="* ]] || continue
		value="${line#*=}"
	done <"$file"
	printf '%s\n' "$value"
}
value() { env_value "$1" "$policy"; }
deployment_group() {
	local node="$1"
	printf '%s-%s\n' "$deployment_group_prefix" "$node"
}
die() {
	printf 'generate-woodpecker-workflows: %s\n' "$*" >&2
	exit 1
}
deploy_debug_level="${DEPLOY_DEBUG_LEVEL:-$(value DEPLOY_DEBUG_LEVEL)}"
deploy_debug_level="${deploy_debug_level:-off}"
case "$deploy_debug_level" in off | warn | debug) ;; *) die 'DEPLOY_DEBUG_LEVEL must be off, warn, or debug' ;; esac
csv_has() {
	local csv=",${1//[[:space:]]/},"
	[[ "$csv" == *",$2,"* ]]
}
app_policy_file() {
	local manifest="$1" app rel
	app="$(env_value APP_ID "$manifest")"
	rel="$(env_value POLICY_FILE "$manifest")"
	[[ "$rel" == "cluster/apps/$app.policy" ]] || die "invalid app policy path: $manifest"
	printf '%s/config/%s\n' "$root" "$rel"
}
render_image_lock() {
	local manifest="$1" app destination key image
	app="$(env_value APP_ID "$manifest")"
	destination="$lock_output_root/$app/images.lock.env"
	install -d -m 700 "$(dirname "$destination")"
	{
		printf '# generated by ops/generate-woodpecker-workflows.sh; do not edit\n'
		for key in $(env_value IMAGE_KEYS "$manifest"); do
			[[ "$key" =~ ^[A-Z][A-Z0-9_]*$ ]] || die "invalid IMAGE_KEYS entry: $manifest/$key"
			image="$(env_value "$key" "$root/ops/images.apps.prod.env")"
			[[ "$image" =~ @sha256:[0-9a-f]{64}$ ]] || die "application image is missing or not digest-pinned: $app/$key"
			printf '%s=%s\n' "$key" "$image"
		done
	} >"$destination"
}

ids=()
followers=()
active_ids=()
reconcile_ids=()
consumer_nodes=()
active_consumer_nodes=()
retired_ids=()
ids_csv=''
while IFS= read -r id; do
	[[ -n "$id" ]] || continue
	[[ "$id" =~ ^[a-z][a-z0-9-]*$ ]] || die "invalid NODE_ID: $id"
	! csv_has "$ids_csv" "$id" || die "duplicate NODE_ID: $id"
	[[ -f "$root/config/cluster/nodes/$id.env" ]] || die "missing node descriptor: $id"
	[[ "$(env_value NODE_ID "$root/config/cluster/nodes/$id.env")" == "$id" ]] || die "descriptor NODE_ID mismatch: $id"
	state="$(env_value NODE_STATE "$root/config/cluster/nodes/$id.env")"
	case "$state" in
	joining) ;;
	draining) reconcile_ids+=("$id") ;;
	active)
		active_ids+=("$id")
		reconcile_ids+=("$id")
		;;
	retired) retired_ids+=("$id") ;;
	*) die "NODE_STATE must be joining, active, draining, or retired: $id" ;;
	esac
	ids+=("$id")
	ids_csv="${ids_csv:+$ids_csv,}$id"
done < <(printf '%s\n' "$(value NODE_IDS)" | tr ',' '\n')
((${#ids[@]} > 0)) || die 'NODE_IDS is empty'
leader_id="$(value LEADER_NODE_ID)"
repo_slug="$(value REPO_SLUG)"
[[ "$repo_slug" =~ ^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$ ]] || die 'REPO_SLUG must be owner/repository'
csv_has "$ids_csv" "$leader_id" || die 'LEADER_NODE_ID is not in NODE_IDS'
[[ "$(env_value NODE_STATE "$root/config/cluster/nodes/$leader_id.env")" == active ]] || die "designated Leader node must be active: $leader_id"
for id in "${ids[@]}"; do
	[[ "$id" == "$leader_id" ]] && continue
	followers+=("$id")
	state="$(env_value NODE_STATE "$root/config/cluster/nodes/$id.env")"
	[[ "$state" == active || "$state" == draining ]] && consumer_nodes+=("$id")
	[[ "$state" == active ]] && active_consumer_nodes+=("$id")
done
((${#followers[@]} > 0)) || die 'at least one follower is required for consumer placement'

write_volumes() {
	cat <<'EOF'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/apps/llm-hub-lite:/opt/apps/llm-hub-lite
      - /opt/platform:/opt/platform
      - /opt/backups/llm-hub-lite:/opt/backups/llm-hub-lite
      - /run/lock/llm-hub-lite:/run/lock/llm-hub-lite
      - /etc/llm-hub-lite:/etc/llm-hub-lite
      - /usr/local/bin/platform-submit:/usr/local/bin/platform-submit:ro
      - /usr/local/bin/platformctl:/usr/local/bin/platformctl:ro
      - /usr/local/bin/configure-app-secrets:/usr/local/bin/configure-app-secrets:ro
      - /usr/local/bin/configure-firewall:/usr/local/bin/configure-firewall:ro
EOF
}

write_consumer_header() {
	local file="$1" app="$2" node="$3" dependencies="$4" dependency
	cat >"$file" <<EOF
# generated by ops/generate-woodpecker-workflows.sh; do not edit
skip_clone: true
when:
  - event: push
    branch: main
    path:
      include:
        - apps/$app/**
        - config/cluster/apps/$app.policy
        - config/cluster/overrides/**/$app.env
        - apps/$app/route*.caddy
        - apps/$app/images.lock.env
      on_empty: false
EOF
	printf '\ndepends_on:\n' >>"$file"
	while IFS= read -r dependency; do
		[[ -n "$dependency" ]] && printf '  - %s\n' "$dependency" >>"$file"
	done < <(printf '%s\n' "$dependencies" | tr ',' '\n')
	printf '  - control-sync-%s\n' "$node" >>"$file"
	printf '  - name: foundation-reconcile-%s\n    optional: true\n' "$node" >>"$file"
	printf '  - name: cluster-reconcile-%s\n    optional: true\n' "$node" >>"$file"
	cat >>"$file" <<EOF

labels:
  node: $node
  deployment: "true"
  target: production
  repo: $repo_slug

concurrency:
  limit: 1
  group: $(deployment_group "$node")

steps:
EOF
}

render_control_sync() {
	local id dependency file command
	id="$1"
	# Control synchronization is node-local.  The host lock and the per-node
	# Woodpecker concurrency group preserve ordering without forcing every
	# follower to wait for the previous follower.
	dependency=''
	command='control-sync'
	if [[ "$id" == "$leader_id" ]]; then
		# Push audit is informational/API housekeeping. Run it independently so
		# planner latency or failure can never delay the real validation gate.
		dependency=''
	else
		dependency="control-sync-$leader_id"
		command='control-verify'
	fi
	file="$output/control-sync-$id.yml"
	cat >"$file" <<EOF
# generated by ops/generate-woodpecker-workflows.sh; do not edit
skip_clone: true
when:
  - event: push
    branch: main

EOF
	if [[ -n "$dependency" ]]; then
		if [[ "$id" == "$leader_id" ]]; then
			# Push audit is telemetry and optional API housekeeping. It must remain
			# visible, but a transient planner failure must never block the real
			# Leader control-sync validation gate.
			printf 'depends_on:\n  - name: %s\n    optional: true\n\n' "$dependency" >>"$file"
		else
			# Followers remain strictly gated on the Leader control-sync result.
			printf 'depends_on:\n  - %s\n\n' "$dependency" >>"$file"
		fi
	fi
	# The Leader performs the expensive full release validation. Followers
	# still fetch and verify the exact commit locally, but are gated on the
	# Leader's successful control gate before any service mutation.
	cat >>"$file" <<EOF
labels:
  node: $id
  deployment: "true"
  target: production
  repo: $repo_slug

concurrency:
  limit: 1
  group: $(deployment_group "$id")

steps:
  control-sync:
    image: llm-hub-lite/deploy-runner:current
    pull: false
EOF
	write_volumes >>"$file"
	cat >>"$file" <<EOF
    commands:
EOF
	if [[ "$command" == control-verify ]]; then
		# During a rolling upgrade a follower may still have the previous
		# platform-submit/controller installed.  That wrapper cannot parse
		# control-verify yet, so fall back to the compatible full control-sync
		# path; once this release is installed, subsequent pushes use the
		# cheaper verification-only path.
		printf '      - if [ -f /opt/platform/control/current/ops/platform-submit.sh ] && grep -q control-verify /opt/platform/control/current/ops/platform-submit.sh; then DEPLOY_DEBUG_LEVEL=%s /usr/local/bin/platform-submit control-verify "$CI_COMMIT_SHA"; else DEPLOY_DEBUG_LEVEL=%s /usr/local/bin/platform-submit control-sync "$CI_COMMIT_SHA"; fi\n' "$deploy_debug_level" "$deploy_debug_level" >>"$file"
	else
		printf '      - DEPLOY_DEBUG_LEVEL=%s /usr/local/bin/platform-submit %s "$CI_COMMIT_SHA"\n' "$deploy_debug_level" "$command" >>"$file"
	fi
}

render_cluster_reconcile() {
	local id="$1" dependency="$2" file
	file="$output/cluster-reconcile-$id.yml"
	cat >"$file" <<EOF
# generated by ops/generate-woodpecker-workflows.sh; do not edit
skip_clone: true
when:
  - event: push
    branch: main
    path:
      include:
        - config/cluster/policy.env
        - config/cluster/nodes/**
        - config/cluster/foundation/**
        - config/Caddyfile
        - compose/foundation/**
        - ops/**
      on_empty: false

EOF
	if [[ -n "$dependency" ]]; then
		# The Leader workflow is path-filtered and is absent on application-only
		# pushes. Keep this edge optional so follower reconciliation still runs
		# for its own selected changes; control-sync remains the strict gate.
		printf 'depends_on:\n  - name: %s\n    optional: true\n  - control-sync-%s\n\n' "$dependency" "$id" >>"$file"
	else
		printf 'depends_on:\n  - control-sync-%s\n\n' "$id" >>"$file"
	fi
	cat >>"$file" <<EOF
labels:
  node: $id
  deployment: "true"
  target: production
  repo: $repo_slug

concurrency:
  limit: 1
  group: $(deployment_group "$id")

steps:
  reconcile:
    image: llm-hub-lite/deploy-runner:current
    pull: false
EOF
	write_volumes >>"$file"
	cat >>"$file" <<EOF
    commands:
      - DEPLOY_DEBUG_LEVEL=$deploy_debug_level /usr/local/bin/platform-submit cluster-reconcile "\$CI_COMMIT_SHA"
EOF
}

render_foundation_reconcile() {
	local id="$1" dependency="${2:-}" file
	file="$output/foundation-reconcile-$id.yml"
	cat >"$file" <<EOF
# generated by ops/generate-woodpecker-workflows.sh; do not edit
skip_clone: true
when:
  - event: push
    branch: main
    path:
      include:
        - compose/foundation/**
        - config/Caddyfile
        - config/foundation-routes.d/**
        - config/cluster/foundation/**
        - ops/foundation/**
        - ops/images.foundation.prod.env
      on_empty: false

depends_on:
  - control-sync-$id
EOF
	if [[ -n "$dependency" ]]; then
		# Foundation changes are leader-first when the Leader job is selected.
		# Keep the edge optional because this workflow is path-filtered: on an
		# application-only push the Leader foundation job is absent and followers
		# must still be allowed to run their ordinary reconciliation.
		printf '  - name: %s\n    optional: true\n' "$dependency" >>"$file"
	fi
	cat >>"$file" <<EOF

labels:
  node: $id
  deployment: "true"
  target: production
  repo: $repo_slug

concurrency:
  limit: 1
  group: $(deployment_group "$id")

steps:
  foundation:
    image: llm-hub-lite/deploy-runner:current
    pull: false
EOF
	write_volumes >>"$file"
	cat >>"$file" <<EOF
    commands:
      - DEPLOY_DEBUG_LEVEL=$deploy_debug_level /usr/local/bin/platform-submit foundation-upgrade "\$CI_COMMIT_SHA"
EOF
}

render_push_audit() {
	local file="$output/push-audit.yml"
	cat >"$file" <<EOF
# generated by ops/generate-woodpecker-workflows.sh; do not edit
# This workflow intentionally has no path filter.  It makes every main push
# visible in Woodpecker, including pushes that do not select a deployment job.
skip_clone: true
when:
  - event: push
    branch: main

labels:
  node: $leader_id
  target: production
  repo: $repo_slug

concurrency:
  limit: 1
  group: llm-hub-lite-push-audit

steps:
  audit:
    image: llm-hub-lite/deploy-runner:current
    pull: false
EOF
	write_volumes >>"$file"
	cat >>"$file" <<EOF
    commands:
      - if [ -f /opt/platform/control/current/ops/woodpecker-plan.sh ] && grep -q 'cat-file -e' /opt/platform/control/current/ops/woodpecker-plan.sh; then CI_COMMIT_BRANCH="\$CI_COMMIT_BRANCH" CI_PIPELINE_NUMBER="\$CI_PIPELINE_NUMBER" CI_COMMIT_SHA="\$CI_COMMIT_SHA" CI_REPO="\$CI_REPO" MIRROR_PATH=/opt/platform/control/mirror.git bash /opt/platform/control/current/ops/woodpecker-plan.sh; elif [ -f /usr/local/bin/woodpecker-plan ] && grep -q 'cat-file -e' /usr/local/bin/woodpecker-plan; then CI_COMMIT_BRANCH="\$CI_COMMIT_BRANCH" CI_PIPELINE_NUMBER="\$CI_PIPELINE_NUMBER" CI_COMMIT_SHA="\$CI_COMMIT_SHA" CI_REPO="\$CI_REPO" MIRROR_PATH=/opt/platform/control/mirror.git bash /usr/local/bin/woodpecker-plan; else printf 'Woodpecker push received sha=%s ref=%s repo=%s\\n' "\$CI_COMMIT_SHA" "\$CI_COMMIT_REF" "\$CI_REPO"; if git --git-dir=/opt/platform/control/mirror.git cat-file -e "\$CI_COMMIT_SHA^{commit}" 2>/dev/null; then git --git-dir=/opt/platform/control/mirror.git show --format= --name-only "\$CI_COMMIT_SHA" | sed '/^\$/d'; else printf 'Woodpecker audit commit %s is not in the local mirror yet; continuing without changed-file listing\\n' "\$CI_COMMIT_SHA"; fi; fi || printf 'Woodpecker audit warning; continuing deployment\\n'
EOF
}

render_consumer_secrets() {
	local app="$1" node="$2" dependency="$3" keys="$4" file key secret_name target_arg='' workflow_name secret_keys
	file="$output/consumer-secrets-$app-$node.yml"
	workflow_name="consumer-secrets-$app-$node"
	secret_keys="$(woodpecker_secret_keys "$app" "$keys")"
	[[ "$node" == "$leader_id" ]] || target_arg=" --target-node $node"
	cat >"$file" <<EOF
# generated by ops/generate-woodpecker-workflows.sh; do not edit
when:
  - event: manual
    branch: main
    evaluate: 'MANUAL_WORKFLOW == "$workflow_name"'
EOF
	if [[ -n "$dependency" ]]; then
		printf '\ndepends_on:\n  - %s\n' "$dependency" >>"$file"
	fi
	cat >>"$file" <<EOF

labels:
  node: $node
  deployment: "true"
  target: production
  repo: $repo_slug

concurrency:
  limit: 1
  group: $(deployment_group "$node")

steps:
  secrets:
    image: llm-hub-lite/deploy-runner:current
    pull: false
EOF
	write_volumes >>"$file"
	printf '    environment:\n' >>"$file"
	while IFS= read -r key; do
		[[ -n "$key" ]] || continue
		secret_name="$(woodpecker_secret_name "$app" "$key")"
		printf '      %s:\n        from_secret: %s\n' "$key" "$secret_name" >>"$file"
	done < <(printf '%s\n' "$secret_keys" | tr ',' '\n')
	cat >>"$file" <<EOF
    commands:
      - /usr/local/bin/configure-app-secrets $app$target_arg --non-interactive
EOF
}
woodpecker_secret_name() {
	local app="$1" wanted="$2" manifest rule key name
	manifest="$root/apps/$app/manifest.env"
	while IFS= read -r rule; do
		[[ -n "$rule" ]] || continue
		key="${rule%%:*}"
		name="${rule#*:}"
		[[ "$key" =~ ^[A-Z][A-Z0-9_]*$ && "$name" =~ ^[A-Za-z_][A-Za-z0-9_-]*$ ]] ||
			die "invalid WOODPECKER_SECRET_NAMES entry: $app/$rule"
		if [[ "$key" == "$wanted" ]]; then
			printf '%s\n' "$name"
			return 0
		fi
	done < <(printf '%s\n' "$(env_value WOODPECKER_SECRET_NAMES "$manifest")" | tr ',' '\n')
	printf '%s' "$wanted" | tr '[:upper:]' '[:lower:]'
}
woodpecker_secret_keys() {
	local app="$1" keys="$2" manifest mapping rule key result=''
	manifest="$root/apps/$app/manifest.env"
	mapping="$(env_value WOODPECKER_SECRET_NAMES "$manifest")"
	# An explicit mapping is an incremental refresh contract: only mapped
	# repository secrets are injected. Unmapped keys remain sourced from the
	# host's existing root-only configuration by configure-app-secrets.
	if [[ -z "$mapping" ]]; then
		printf '%s\n' "$keys"
		return 0
	fi
	while IFS= read -r rule; do
		[[ -n "$rule" ]] || continue
		key="${rule%%:*}"
		csv_has "$keys" "$key" || continue
		result="${result:+$result,}$key"
	done < <(printf '%s\n' "$mapping" | tr ',' '\n')
	printf '%s\n' "$result"
}
conditional_secret_keys() {
	local manifest="$1" node="${2:-}" rule selector expected keys config_file override_file value result=''
	config_file="$(dirname "$manifest")/$(env_value CONFIG_FILE "$manifest")"
	override_file="$root/config/cluster/overrides/$node/$(env_value APP_ID "$manifest").env"
	while IFS= read -r rule; do
		[[ -n "$rule" ]] || continue
		selector="${rule%%=*}"
		expected="${rule#*=}"
		keys="${expected#*|}"
		expected="${expected%%|*}"
		value="$(env_value "$selector" "$override_file")"
		[[ -n "$value" ]] || value="$(env_value "$selector" "$config_file")"
		[[ "$value" == "$expected" ]] || continue
		result="${result:+$result,}$keys"
	done < <(printf '%s\n' "$(env_value CONDITIONAL_SECRET_KEYS "$manifest")" | tr ';' '\n')
	printf '%s\n' "$result"
}

render_consumer_stage() {
	local app="$1" node="$2" dependency="$3" file manifest migration_from stage_secret_keys generated_keys key secret_name
	file="$output/consumer-stage-$app-$node.yml"
	manifest="$root/apps/$app/manifest.env"
	migration_from="$(env_value IDENTITY_MIGRATION_FROM_APP_ID "$manifest")"
	write_consumer_header "$file" "$app" "$node" "$dependency"
	cat >>"$file" <<EOF
  stage:
    image: llm-hub-lite/deploy-runner:current
    pull: false
EOF
	write_volumes >>"$file"
	stage_secret_keys=''
	if [[ "$(env_value RUNTIME_ENV_PROVISION "$manifest")" == stage ]]; then
		stage_secret_keys="$(env_value NODE_SECRET_KEYS "$manifest"),$(conditional_secret_keys "$manifest" "$node")"
	fi
	if [[ -n "$stage_secret_keys" ]]; then
		generated_keys="$(env_value GENERATED_SECRET_KEYS "$manifest")"
		printf '    environment:\n' >>"$file"
		while IFS= read -r key; do
			[[ -n "$key" ]] || continue
			csv_has "$generated_keys" "$key" && continue
			secret_name="$(woodpecker_secret_name "$app" "$key")"
			printf '      %s:\n        from_secret: %s\n' "$key" "$secret_name" >>"$file"
		done < <(printf '%s\n' "$stage_secret_keys" | tr ',' '\n' | awk 'NF && !seen[$0]++')
	fi
	if [[ -n "$migration_from" ]]; then
		cat >>"$file" <<EOF
    commands:
      - bash /opt/platform/control/current/ops/migrate-app-identity.sh prepare $app
EOF
	else
		printf '    commands:\n' >>"$file"
	fi
	cat >>"$file" <<EOF
      - /usr/local/bin/configure-app-secrets $app --target-node $node --ensure-generated
EOF
	if [[ -n "$stage_secret_keys" ]]; then
		printf '      - /usr/local/bin/configure-app-secrets %s --target-node %s --non-interactive\n' "$app" "$node" >>"$file"
	fi
	if [[ -n "$migration_from" ]]; then
		cat >>"$file" <<EOF
      - DEPLOY_DEBUG_LEVEL=$deploy_debug_level CONSUMER_APP_ID=$app /usr/local/bin/platform-submit consumer-stage "\$CI_COMMIT_SHA" || { status=\$?; rollback_status=0; IDENTITY_MIGRATION_MANIFEST=/opt/platform/control/releases/"\$CI_COMMIT_SHA"/apps/$app/manifest.env bash /opt/platform/control/releases/"\$CI_COMMIT_SHA"/ops/migrate-app-identity.sh rollback $app || rollback_status=\$?; /usr/local/bin/platformctl recover || true; if [ "\$rollback_status" -ne 0 ]; then exit "\$rollback_status"; fi; exit "\$status"; }
EOF
	else
		cat >>"$file" <<EOF
      - DEPLOY_DEBUG_LEVEL=$deploy_debug_level CONSUMER_APP_ID=$app /usr/local/bin/platform-submit consumer-stage "\$CI_COMMIT_SHA"
EOF
	fi
}

render_consumer_publish() {
	local app="$1" dependency="$2" file
	file="$output/consumer-publish-$app.yml"
	write_consumer_header "$file" "$app" "$leader_id" "$dependency"
	cat >>"$file" <<EOF
  publish:
    image: llm-hub-lite/deploy-runner:current
    pull: false
EOF
	write_volumes >>"$file"
	cat >>"$file" <<EOF
    commands:
      - DEPLOY_DEBUG_LEVEL=$deploy_debug_level CONSUMER_APP_ID=$app /usr/local/bin/platform-submit consumer-publish "\$CI_COMMIT_SHA"
EOF
}

render_direct_publish() {
	local app="$1" node="$2" dependency="$3" file
	file="$output/direct-publish-$app.yml"
	write_consumer_header "$file" "$app" "$node" "$dependency"
	cat >>"$file" <<EOF
  publish:
    image: llm-hub-lite/deploy-runner:current
    pull: false
EOF
	write_volumes >>"$file"
	cat >>"$file" <<EOF
    commands:
      - DEPLOY_DEBUG_LEVEL=$deploy_debug_level DIRECT_APP_ID=$app /usr/local/bin/platform-submit direct-publish "\$CI_COMMIT_SHA"
EOF
}

render_consumer_stop() {
	local app="$1" node="$2" dependency="$3" file
	file="$output/consumer-stop-$app-$node.yml"
	write_consumer_header "$file" "$app" "$node" "$dependency"
	cat >>"$file" <<EOF
  stop:
    image: llm-hub-lite/deploy-runner:current
    pull: false
EOF
	write_volumes >>"$file"
	cat >>"$file" <<EOF
    commands:
      - DEPLOY_DEBUG_LEVEL=$deploy_debug_level CONSUMER_APP_ID=$app /usr/local/bin/platform-submit consumer-stop "\$CI_COMMIT_SHA"
EOF
}

render_consumer_finalize() {
	local app="$1" node="$2" dependency="$3" file manifest migration_from
	file="$output/consumer-finalize-$app-$node.yml"
	manifest="$root/apps/$app/manifest.env"
	migration_from="$(env_value IDENTITY_MIGRATION_FROM_APP_ID "$manifest")"
	write_consumer_header "$file" "$app" "$node" "$dependency"
	cat >>"$file" <<EOF
  finalize:
    image: llm-hub-lite/deploy-runner:current
    pull: false
EOF
	write_volumes >>"$file"
	cat >>"$file" <<EOF
    commands:
      - DEPLOY_DEBUG_LEVEL=$deploy_debug_level SINGLETON_FINAL_STOP=1 CONSUMER_APP_ID=$app /usr/local/bin/platform-submit consumer-stop "\$CI_COMMIT_SHA"
EOF
	if [[ -n "$migration_from" ]]; then
		printf '      - bash /opt/platform/control/current/ops/migrate-app-identity.sh finalize %s\n' "$app" >>"$file"
	fi
}

render_consumer_workflows() {
	local manifest="$1" app placement upstream ingress policy_file enabled nodes node previous='' publish_name seen='' count=0 undesired='' primary_key primary stage_dependency='' target cluster_keys node_keys conditional_keys secret_keys migration_from key migration_value finalize_dependency
	app="$(env_value APP_ID "$manifest")"
	placement="$(env_value PLACEMENT "$manifest")"
	upstream="$(env_value UPSTREAM_MODE "$manifest")"
	ingress="$(env_value INGRESS_MODE "$manifest")"
	ingress="${ingress:-leader-proxy}"
	[[ "$app" == "$(basename "$(dirname "$manifest")")" && "$app" =~ ^[a-z][a-z0-9-]*$ ]] || die "invalid APP_ID: $manifest"
	[[ "$(env_value MANIFEST_VERSION "$manifest")" == 5 ]] || die "unsupported application manifest version: $manifest"
	[[ "$placement" == consumer ]] || die "application placement must be consumer: $manifest"
	policy_file="$(app_policy_file "$manifest")"
	[[ -f "$policy_file" ]] || die "missing app policy: $app"
	enabled="$(env_value ENABLED "$policy_file")"
	case "$enabled" in true | false) ;; *) die "app policy ENABLED must be true or false: $app" ;; esac
	nodes="$(env_value NODES "$policy_file")"
	[[ -n "$nodes" ]] || die "application policy NODES is empty: $app"
	while IFS= read -r node; do
		[[ "$node" =~ ^[a-z][a-z0-9-]*$ ]] || die "invalid consumer node: $app/$node"
		if ! csv_has "$ids_csv" "$node"; then
			# Direct applications may be committed ahead of a joining inventory
			# entry. Defer workflow generation until that follower is enrolled;
			# runtime validation still rejects an enabled placement that is absent.
			[[ "$ingress" == direct ]] && {
				printf 'generate-woodpecker-workflows: deferring direct app until node is enrolled: %s/%s\n' "$app" "$node" >&2
				return 0
			}
			die "consumer node is absent from NODE_IDS: $app/$node"
		fi
		[[ "$node" != "$leader_id" ]] || die "consumer node must be an active follower: $app/$node"
		if [[ "$enabled" == true ]]; then
			if [[ "$(env_value NODE_STATE "$root/config/cluster/nodes/$node.env")" != active ]]; then
				[[ "$ingress" == direct ]] && {
					printf 'generate-woodpecker-workflows: deferring direct app until node is active: %s/%s\n' "$app" "$node" >&2
					return 0
				}
				die "consumer node must be an active follower: $app/$node"
			fi
		fi
		! csv_has "$seen" "$node" || die "duplicate consumer node: $app/$node"
		seen="${seen:+$seen,}$node"
		count=$((count + 1))
	done < <(printf '%s\n' "$nodes" | tr ',' '\n')
	case "$upstream" in
	singleton) ((count == 1)) || die "singleton application must target exactly one follower: $app" ;;
	active-active) ((count >= 1)) || die "$upstream application requires a follower: $app" ;;
	active-passive)
		((count >= 1)) || die "$upstream application requires a follower: $app"
		primary_key="$(env_value PRIMARY_NODE_KEY "$manifest")"
		[[ "$primary_key" =~ ^[A-Z][A-Z0-9_]*$ ]] || die "active-passive application requires PRIMARY_NODE_KEY: $app"
		primary="$(env_value "$primary_key" "$policy_file")"
		csv_has "$nodes" "$primary" || die "active-passive primary is absent from NODES: $app/$primary"
		;;
	*) die "unsupported UPSTREAM_MODE for $app: $upstream" ;;
	esac
	migration_from="$(env_value IDENTITY_MIGRATION_FROM_APP_ID "$manifest")"
	if [[ -n "$migration_from" ]]; then
		[[ "$upstream" == singleton && "$migration_from" =~ ^[a-z][a-z0-9-]*$ && "$migration_from" != "$app" ]] || die "invalid identity migration source: $app/$migration_from"
		for key in IDENTITY_MIGRATION_FROM_DATA_ROOT_REL IDENTITY_MIGRATION_FROM_RUNTIME_ENV_FILE IDENTITY_MIGRATION_FROM_COMPOSE_PROJECT IDENTITY_MIGRATION_FROM_NETWORK IDENTITY_MIGRATION_FROM_ENV_PREFIX IDENTITY_MIGRATION_TO_ENV_PREFIX IDENTITY_MIGRATION_TO_NETWORK; do
			migration_value="$(env_value "$key" "$manifest")"
			[[ -n "$migration_value" ]] || die "identity migration requires $key: $app"
		done
	fi
	if [[ "$app" == newapi && "$enabled" == true ]]; then
		for primary_key in NEW_API_MIGRATION_NODE_ID NEW_API_BACKUP_NODE_ID; do
			primary="$(env_value "$primary_key" "$policy_file")"
			csv_has "$nodes" "$primary" || die "$primary_key is absent from New API NODES: $primary"
		done
	fi
	if [[ "$enabled" == true ]]; then
		while IFS= read -r node; do
			# Active-active replicas are independent.  Singleton and active-passive
			# ordering is applied below where the application semantics require it.
			stage_dependency=''
			if [[ "$upstream" == active-passive && "$node" != "$primary" ]]; then
				stage_dependency="consumer-stage-$app-$primary"
			fi
			render_consumer_stage "$app" "$node" "$stage_dependency"
		done < <(printf '%s\n' "$nodes" | tr ',' '\n')
	fi
	# `previous` is retained for publish dependencies below; it is not used to
	# chain independent stage jobs.
	previous=''
	if [[ "$enabled" == true ]]; then
		while IFS= read -r node; do
			[[ -n "$node" ]] || continue
			previous="${previous}${previous:+,}consumer-stage-$app-$node"
		done < <(printf '%s\n' "$nodes" | tr ',' '\n')
	fi
	if [[ "$ingress" == direct && "$enabled" == true ]]; then
		target="${nodes%%,*}"
		render_direct_publish "$app" "$target" "$previous"
		publish_name="direct-publish-$app"
	else
		# Disabled direct apps still need a Leader cleanup transaction, but must
		# never invoke direct-publish (which assumes an active follower listener).
		render_consumer_publish "$app" "$previous"
		publish_name="consumer-publish-$app"
	fi
	for node in "${consumer_nodes[@]}"; do
		if [[ "$enabled" != true ]] || ! csv_has "$nodes" "$node"; then
			undesired="${undesired}${node}"$'\n'
		fi
	done
	previous="$publish_name"
	while IFS= read -r node; do
		[[ -n "$node" ]] || continue
		render_consumer_stop "$app" "$node" "$publish_name"
	done <<<"$undesired"
	if [[ "$enabled" == true && "$upstream" == singleton ]]; then
		target="${nodes%%,*}"
		# Finalization must wait for all stale-node cleanup, but those cleanup
		# jobs themselves run concurrently on their respective node groups.
		finalize_dependency="$publish_name"
		while IFS= read -r node; do
			[[ -n "$node" ]] || continue
			finalize_dependency="${finalize_dependency}${finalize_dependency:+,}consumer-stop-$app-$node"
		done <<<"$undesired"
		render_consumer_finalize "$app" "$target" "$finalize_dependency"
	fi
	if [[ "$enabled" == true ]]; then
		cluster_keys="$(env_value CLUSTER_SECRET_KEYS "$manifest")"
		node_keys="$(env_value NODE_SECRET_KEYS "$manifest")"
		conditional_keys="$(conditional_secret_keys "$manifest" "$leader_id")"
		# Conditional credentials for singleton consumers belong only to the
		# selected follower.  Cluster-wide secrets still need a Leader workflow;
		# active-active consumers continue to provision conditional credentials on
		# the Leader and each selected follower.
		if [[ -n "$cluster_keys" || ("$upstream" != singleton && -n "$conditional_keys") ]]; then
			render_consumer_secrets "$app" "$leader_id" '' "$cluster_keys,$conditional_keys"
		fi
		# Node-local secrets belong only on the nodes selected by this app's
		# placement policy.  Cleanup workflows above still cover active nodes
		# removed from placement, but they must not receive new credentials.
		while IFS= read -r node; do
			[[ -n "$node" ]] || continue
			conditional_keys="$(conditional_secret_keys "$manifest" "$node")"
			secret_keys="$cluster_keys"
			[[ -z "$conditional_keys" ]] || secret_keys="${secret_keys:+$secret_keys,}$conditional_keys"
			[[ -z "$node_keys" ]] || secret_keys="${secret_keys:+$secret_keys,}$node_keys"
			[[ -n "$secret_keys" ]] || continue
			render_consumer_secrets "$app" "$node" '' "$secret_keys"
		done < <(printf '%s\n' "$nodes" | tr ',' '\n')
	fi
}

render_manual_node() {
	local kind="$1" id="$2" previous="$3" file="$4" command submit workflow_name
	workflow_name="${file##*/}"
	workflow_name="${workflow_name%.yml}"
	case "$kind" in
	foundation) command='foundation-upgrade "$CI_COMMIT_SHA"' ;;
	runner) command='upgrade-runner' ;;
	rollback) command='rollback "${ROLLBACK_TARGET:-previous}"' ;;
	retire) command='node-retire "$CI_COMMIT_SHA"' ;;
	*) die "unknown manual workflow kind: $kind" ;;
	esac
	submit="/usr/local/bin/platform-submit $command"
	[[ "$kind" == runner ]] && submit='/usr/local/bin/upgrade-runner'
	cat >"$file" <<EOF
# generated by ops/generate-woodpecker-workflows.sh; do not edit
when:
  - event: manual
    branch: main
    evaluate: 'MANUAL_WORKFLOW == "$workflow_name"'
EOF
	[[ -z "$previous" ]] || printf '\ndepends_on:\n  - %s\n' "$previous" >>"$file"
	cat >>"$file" <<EOF

labels:
  node: $id
  deployment: "true"
  target: production
  repo: $repo_slug

concurrency:
  limit: 1
  group: $(deployment_group "$id")

steps:
  $kind:
    image: llm-hub-lite/deploy-runner:current
    pull: false
EOF
	write_volumes >>"$file"
	cat >>"$file" <<EOF
      - /usr/local/bin/deploy-controller:/usr/local/bin/deploy-controller:ro
      - /usr/local/bin/git-auth.sh:/usr/local/bin/git-auth.sh:ro
      - /usr/local/bin/backup-platform:/usr/local/bin/backup-platform:ro
      - /usr/local/bin/upgrade-runner:/usr/local/bin/upgrade-runner:ro
    commands:
      - $submit
EOF
}

remove_generated() {
	local file
	for file in "$output"/*.yml; do
		[[ -f "$file" ]] || continue
		head -n1 "$file" | grep -Fq 'generated by ops/generate-woodpecker-workflows.sh' || continue
		rm -f -- "$file"
	done
	for file in "$lock_output_root"/*/images.lock.env; do
		[[ -f "$file" ]] || continue
		head -n1 "$file" | grep -Fq 'generated by ops/generate-woodpecker-workflows.sh' || continue
		rm -f -- "$file"
	done
}
check_dependency_closure() {
	local file dependency
	for file in "$output"/*.yml; do
		[[ -f "$file" ]] || continue
		while IFS= read -r dependency; do
			[[ -n "$dependency" ]] || continue
			[[ -f "$output/$dependency.yml" ]] || die "workflow dependency does not exist: $file -> $dependency"
		done < <(awk '/^depends_on:/ {active=1; next} active && /^  - name: / {sub(/^  - name: /, ""); print; next} active && /^  - / {sub(/^  - /, ""); print; next} active {active=0}' "$file")
	done
}
render_all() {
	local manifest id previous
	install -d -m 700 "$output"
	for id in "${ids[@]}"; do
		render_control_sync "$id" ''
	done
	render_push_audit
	for id in "${reconcile_ids[@]}"; do
		if [[ "$id" == "$leader_id" ]]; then
			render_foundation_reconcile "$id" ''
		else
			render_foundation_reconcile "$id" "foundation-reconcile-$leader_id"
		fi
	done
	for manifest in "$root"/apps/*/manifest.env; do
		[[ -f "$manifest" ]] || continue
		render_image_lock "$manifest"
		render_consumer_workflows "$manifest"
	done
	render_cluster_reconcile "$leader_id" ''
	for id in "${reconcile_ids[@]}"; do
		[[ "$id" == "$leader_id" ]] && continue
		render_cluster_reconcile "$id" "cluster-reconcile-$leader_id"
	done
	previous=''
	render_manual_node foundation "$leader_id" "$previous" "$output/foundation-upgrade-$leader_id.yml"
	previous="foundation-upgrade-$leader_id"
	for id in "${active_ids[@]}"; do
		[[ "$id" == "$leader_id" ]] && continue
		render_manual_node foundation "$id" "$previous" "$output/foundation-upgrade-$id.yml"
		previous="foundation-upgrade-$id"
	done
	previous=''
	render_manual_node runner "$leader_id" "$previous" "$output/runner-upgrade-$leader_id.yml"
	previous="runner-upgrade-$leader_id"
	for id in "${active_ids[@]}"; do
		[[ "$id" == "$leader_id" ]] && continue
		render_manual_node runner "$id" "$previous" "$output/runner-upgrade-$id.yml"
		previous="runner-upgrade-$id"
	done
	previous=''
	for id in "${consumer_nodes[@]}"; do
		render_manual_node rollback "$id" "$previous" "$output/rollback-$id.yml"
		previous="rollback-$id"
	done
	render_manual_node rollback "$leader_id" "$previous" "$output/rollback-$leader_id.yml"
	# Bash 3.2 treats an empty array expansion as unbound under `set -u`.
	# The default cluster has no retired nodes, so tolerate the one empty item.
	for id in "${retired_ids[@]-}"; do
		[[ -n "$id" ]] || continue
		render_manual_node retire "$id" '' "$output/node-retire-$id.yml"
	done
	check_dependency_closure
}

copy_generated_stage() {
	local stage="$1" file target
	for file in "$stage"/*.yml; do
		[[ -f "$file" ]] || continue
		target="$output/$(basename "$file")"
		if ! cp -p "$file" "$target"; then return 1; fi
	done
	for file in "$stage"/apps/*/images.lock.env; do
		[[ -f "$file" ]] || continue
		target="$lock_output_root/$(basename "$(dirname "$file")")/images.lock.env"
		install -d -m 700 "$(dirname "$target")"
		if ! cp -p "$file" "$target"; then return 1; fi
	done
}

generate_transaction() {
	local stage backup real_output real_lock_output_root file relative
	install -d -m 700 "$output" "$lock_output_root"
	stage="$(mktemp -d "${output}.staging.XXXXXX")"
	real_output="$output"
	real_lock_output_root="$lock_output_root"
	output="$stage"
	lock_output_root="$stage/apps"
	if ! render_all; then
		output="$real_output"
		lock_output_root="$real_lock_output_root"
		rm -rf -- "$stage"
		return 1
	fi
	output="$real_output"
	lock_output_root="$real_lock_output_root"
	# Render and dependency validation have succeeded. Keep a private copy of
	# every generated artifact so an interrupted apply can restore it exactly.
	backup="$(mktemp -d "${output}.backup.XXXXXX")"
	for file in "$output"/*.yml; do
		[[ -f "$file" ]] || continue
		head -n1 "$file" | grep -Fq 'generated by ops/generate-woodpecker-workflows.sh' || continue
		cp -p "$file" "$backup/$(basename "$file")" || {
			rm -rf -- "$stage" "$backup"
			return 1
		}
	done
	for file in "$lock_output_root"/*/images.lock.env; do
		[[ -f "$file" ]] || continue
		head -n1 "$file" | grep -Fq 'generated by ops/generate-woodpecker-workflows.sh' || continue
		relative="apps/$(basename "$(dirname "$file")")/images.lock.env"
		install -d -m 700 "$backup/apps/$(basename "$(dirname "$file")")"
		cp -p "$file" "$backup/$relative" || {
			rm -rf -- "$stage" "$backup"
			return 1
		}
	done
	if ! remove_generated || ! copy_generated_stage "$stage"; then
		# Best-effort rollback is deliberately explicit. The old set is restored
		# before the caller reports failure, so a partial workflow set is never
		# left for Woodpecker to execute.
		remove_generated || true
		for file in "$backup"/*.yml; do
			[[ -f "$file" ]] || continue
			cp -p "$file" "$output/$(basename "$file")" || true
		done
		for file in "$backup"/apps/*/images.lock.env; do
			[[ -f "$file" ]] || continue
			target="$lock_output_root/$(basename "$(dirname "$file")")/images.lock.env"
			install -d -m 700 "$(dirname "$target")"
			cp -p "$file" "$target" || true
		done
		rm -rf -- "$stage" "$backup"
		return 1
	fi
	rm -rf -- "$stage" "$backup"
}

case "$mode" in
generate) generate_transaction || die 'unable to apply generated workflow set atomically' ;;
--check)
	tmp="$(mktemp -d)"
	trap 'rm -rf -- "$tmp"' EXIT
	real_output="$output"
	real_lock_output_root="$lock_output_root"
	output="$tmp"
	lock_output_root="$tmp/apps"
	render_all
	output="$real_output"
	lock_output_root="$real_lock_output_root"
	for file in "$tmp"/*.yml; do
		target="$output/$(basename "$file")"
		cmp -s "$file" "$target" || die "workflow is stale or differs: $target"
	done
	for file in "$tmp"/apps/*/images.lock.env; do
		[[ -f "$file" ]] || continue
		app="$(basename "$(dirname "$file")")"
		target="$lock_output_root/$app/images.lock.env"
		cmp -s "$file" "$target" || die "application image lock is stale or differs: $target"
	done
	for file in "$output"/*.yml; do
		[[ -f "$file" ]] || continue
		if head -n1 "$file" | grep -Fq 'generated by ops/generate-woodpecker-workflows.sh'; then
			[[ -f "$tmp/$(basename "$file")" ]] || die "stale generated workflow: $file"
		fi
	done
	check_dependency_closure
	;;
*) die 'usage: generate-woodpecker-workflows.sh [generate|--check]' ;;
esac
